# Generated by Django 5.2.16 on 2026-07-13 16:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('id_card', "Pièce d'identité"), ('proof_address', 'Justificatif domicile'), ('financial', 'Document financier'), ('other', 'Autre')], default='other', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('file_url', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('pending_validation', 'En attente de validation'), ('approved', 'Approuvé'), ('posted', 'Comptabilisé'), ('rejected', 'Rejeté'), ('reversed', 'Annulé (contre-passé)')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.fintechuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KycProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc_status', models.CharField(choices=[('Validé', 'Validé'), ('En attente', 'En attente')], default='En attente', max_length=12)),
                ('risk_score', models.CharField(choices=[('Bas', 'Bas'), ('Moyen', 'Moyen'), ('Élevé', 'Élevé')], default='Moyen', max_length=10)),
                ('kyc_level', models.CharField(default='T1', max_length=4)),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=Decimal('50000'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to='accounts.fintechuser')),
            ],
        ),
    ]
