# Generated by Django 5.2.16 on 2026-07-13 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('SIEGE', 'Siège'), ('RURALE', 'Rurale'), ('URBAINE', 'Urbaine'), ('POINT_SERVICE', 'Point de service')], default='URBAINE', max_length=20)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('manager_sub', models.CharField(blank=True, max_length=255)),
                ('compliance_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('FERMEE', 'Fermée')], default='ACTIF', max_length=10)),
                ('suspended_reason', models.CharField(blank=True, max_length=255)),
                ('closed_reason', models.CharField(blank=True, max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='agencies_ag_status_b4cb2f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Avertissement'), ('DANGER', 'Danger')], default='INFO', max_length=10)),
                ('message', models.CharField(max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='agencies.agency')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
