# Generated by Django 5.2.16 on 2026-07-15 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agencyreactivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé')], default='PENDING', max_length=12)),
                ('delta_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('assigned_to', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_final_closure', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='agencies.agency')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
