# Generated by Django 5.2.16 on 2026-07-15 17:31

import agencies.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_agencyreconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyActionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('SUSPEND', 'Suspendre'), ('CLOSE', 'Fermer'), ('UNLOCK_TEMPORARY', 'Déverrouillage temporaire'), ('REOPEN', 'Réouverture')], max_length=20)),
                ('reason', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='agency_action_requests/')),
                ('requested_by', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', "En attente d'approbation"), ('REJECTED', 'Rejetée'), ('EXECUTED', 'Exécutée')], default='PENDING_APPROVAL', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_requests', to='agencies.agency')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgencyActionChallenge',
            fields=[
                ('id', models.CharField(default=agencies.models._generate_challenge_id, max_length=36, primary_key=True, serialize=False)),
                ('approver_sub', models.CharField(max_length=255)),
                ('code_hash', models.CharField(max_length=128)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='agencies.agencyactionrequest')),
            ],
        ),
    ]
