# Generated by Django 5.2.16 on 2026-07-16 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_agencyactionrequest_agencyactionchallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyComplianceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('components', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_snapshots', to='agencies.agency')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
    ]
