# Generated by Django 5.2.16 on 2026-07-16 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_agencycompliancesnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_type', models.CharField(choices=[('SIEGE', 'Siège'), ('RURALE', 'Rurale'), ('URBAINE', 'Urbaine'), ('POINT_SERVICE', 'Point de service')], max_length=20)),
                ('to_type', models.CharField(choices=[('SIEGE', 'Siège'), ('RURALE', 'Rurale'), ('URBAINE', 'Urbaine'), ('POINT_SERVICE', 'Point de service')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='IN_PROGRESS', max_length=12)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_plans', to='agencies.agency')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvolutionPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_done', models.BooleanField(default=False)),
                ('done_by', models.CharField(blank=True, max_length=255)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='agencies.evolutionplan')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
