# Generated by Django 5.2.16 on 2026-07-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0006_evolutionplan_evolutionplanitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionApproverConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('agency', 'Action Agence'), ('transaction', 'Transaction'), ('caisse_regularization', 'Régularisation Caisse'), ('caisse_withdrawal', 'Retrait Caisse')], default='agency', max_length=30)),
                ('action_type', models.CharField(max_length=50)),
                ('approver_sub', models.CharField(max_length=255)),
                ('approver_name', models.CharField(blank=True, max_length=200)),
                ('approver_role', models.CharField(blank=True, max_length=50)),
                ('assigned_by', models.CharField(blank=True, max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scope', 'action_type'],
                'unique_together': {('scope', 'action_type', 'approver_sub')},
            },
        ),
    ]
