# Generated by Django 5.2.16 on 2026-07-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0007_actionapproverconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionapproverconfig',
            name='approver_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
