# Generated by Django 5.2.16 on 2026-07-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FintechUser',
            fields=[
                ('sub', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(default='client', max_length=40)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('farmer_id', models.CharField(blank=True, max_length=64)),
                ('national_id', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
