# Generated by Django 5.2.16 on 2026-07-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0005_analysisrule_linefinding_needssheet_document_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='linefinding',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
