# Generated by Django 5.2.16 on 2026-07-20 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_migrate_legacy_vocabulary'),
        ('credits', '0006_alter_analysisrule_id_alter_linefinding_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditguarantee',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guarantees', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='creditguarantee',
            name='covered_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='creditguarantee',
            name='guarantee_type',
            field=models.CharField(choices=[('epargne', 'Nantissement épargne'), ('morale', 'Caution solidaire'), ('materiel', 'Gage matériel'), ('foncier', 'Hypothèque / foncier')], max_length=10),
        ),
    ]
