# Generated by Django 5.2.16 on 2026-07-20 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0007_creditguarantee_asset_creditguarantee_covered_amount_and_more'),
        ('dataio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplication',
            name='needs_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_applications', to='dataio.datasource'),
        ),
    ]
