# Generated by Django 5.2.16 on 2026-07-20 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('assets', '0003_migrate_legacy_vocabulary'),
        ('credits', '0008_creditapplication_needs_source'),
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditguarantee',
            name='consent_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditguarantee',
            name='consent_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='creditguarantee',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cautions_donnees', to='accounts.fintechuser'),
        ),
        migrations.AlterField(
            model_name='creditguarantee',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de confirmation'), ('pending_consent', 'En attente du consentement du garant'), ('consented', 'Consentie par le garant'), ('declined', 'Refusée par le garant'), ('active', 'Active / constituée'), ('released', 'Levée / libérée'), ('expired', 'Expirée (délai dépassé)'), ('called', 'Appelée (défaut du débiteur)')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='creditguarantee',
            index=models.Index(fields=['guarantor', 'guarantee_type', 'status'], name='credits_cre_guarant_b311ef_idx'),
        ),
    ]
