# Generated by Django 5.2.16 on 2026-07-20 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0009_creditguarantee_consent_expires_at_and_more'),
        ('dataio', '0002_datasource_credit_application_datasource_sha256_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaremeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('libelle', models.CharField(blank=True, max_length=200)),
                ('points', models.JSONField(default=list)),
                ('parametres', models.JSONField(blank=True, default=dict)),
                ('actif', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ReferentielFiliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('filiere', models.CharField(max_length=100)),
                ('value_chain_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('unite_reference', models.CharField(default='ha', max_length=30)),
                ('couts_modules', models.JSONField(default=dict)),
                ('rendement_ref', models.JSONField(default=dict)),
                ('n_cas_reels', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('indicatif', 'Indicatif (plages estimées)'), ('appris', 'Appris (N ≥ 30 dossiers réels)')], default='indicatif', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('actif', models.BooleanField(default=True)),
                ('devise', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AnalyseCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_source_revision', models.PositiveIntegerField(default=1)),
                ('needs_source_sha256', models.CharField(blank=True, max_length=64)),
                ('duree_mois', models.PositiveIntegerField()),
                ('differe_mois', models.PositiveIntegerField(default=0)),
                ('mode_differe', models.CharField(default='interets_seuls', max_length=20)),
                ('taux_annuel', models.DecimalField(decimal_places=3, max_digits=6)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('devise', models.CharField(default='USD', max_length=3)),
                ('criteres', models.JSONField(default=dict)),
                ('dscr', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('dscr_stress', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('score_global', models.DecimalField(decimal_places=1, max_digits=5)),
                ('recommandation', models.CharField(choices=[('approbation', 'Approbation recommandée'), ('approbation_cond', 'Approbation sous conditions'), ('revue', 'Revue approfondie requise'), ('refus', 'Refus recommandé')], max_length=20)),
                ('indicateurs_hors_plage', models.JSONField(default=list)),
                ('justifications', models.JSONField(default=list)),
                ('echeancier', models.JSONField(default=list)),
                ('poids_appliques', models.JSONField(default=dict)),
                ('baremes_appliques', models.JSONField(default=dict)),
                ('execute_le', models.DateTimeField(auto_now_add=True)),
                ('execute_par', models.CharField(blank=True, max_length=255)),
                ('version_moteur', models.CharField(default='4.0', max_length=10)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='credits.creditapplication')),
                ('needs_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='dataio.datasource')),
                ('referentiel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credits.referentielfiliere')),
            ],
            options={
                'ordering': ['-execute_le', '-id'],
                'indexes': [models.Index(fields=['application', '-execute_le'], name='credits_ana_applica_1d6a8a_idx')],
            },
        ),
    ]
