# Generated by Django 5.2.16 on 2026-07-21 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0010_baremescore_referentielfiliere_analysecredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaremeRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bareme_code', models.CharField(db_index=True, max_length=40)),
                ('points', models.JSONField(default=list)),
                ('parametres', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', "Proposée (en attente d'activation)"), ('active', 'Active'), ('archived', 'Archivée (remplacée)'), ('rejected', 'Rejetée par le comité')], default='draft', max_length=10)),
                ('impact_preview', models.JSONField(blank=True, default=dict)),
                ('comment', models.TextField(blank=True)),
                ('proposed_by_sub', models.CharField(max_length=255)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by_sub', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bareme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='credits.baremescore')),
            ],
            options={
                'ordering': ['bareme_code', '-version', '-id'],
                'indexes': [models.Index(fields=['bareme_code', 'status'], name='credits_bar_bareme__e3d9fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommitteeVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_sub', models.CharField(max_length=255)),
                ('decision', models.CharField(choices=[('approve', "Pour l'approbation"), ('reject', 'Pour le rejet')], max_length=10)),
                ('comment', models.TextField()),
                ('conditions', models.TextField(blank=True)),
                ('quorum_at_vote', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_votes', to='credits.creditapplication')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['application', 'created_at'], name='credits_com_applica_4317d0_idx')],
                'constraints': [models.UniqueConstraint(fields=('application', 'voter_sub'), name='unique_committee_vote_per_member')],
            },
        ),
    ]
