# Generated by Django 5.2.16 on 2026-07-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0011_baremerevision_committeevote'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysecredit',
            name='taux_propose',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='quantite_reference',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Quantité du projet dans l'unité du référentiel filière (ha, ruche, sujet, m2, sac, tonne…).", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='unite_reference',
            field=models.CharField(blank=True, help_text="Unité de `quantite_reference` — doit être celle du référentiel de la filière, sinon l'analyse est refusée.", max_length=30),
        ),
    ]
