# Generated by Django 5.2.16 on 2026-07-22 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0008_add_phone_to_approver_config'),
        ('credits', '0012_dimension_reference_et_taux_propose'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplication',
            name='agency',
            field=models.ForeignKey(blank=True, help_text="Agence d'instruction, déduite de l'agent qui monte le dossier. Vide = rattachement indéterminé (dossier antérieur au champ, ou créateur sans affectation).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_applications', to='agencies.agency'),
        ),
    ]
