# Generated by Django 5.2.16 on 2026-07-22 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('credits', '0013_creditapplication_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuaranteeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covered_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposée (en attente de validation)'), ('validated', "Validée par l'agent"), ('refused', "Refusée par l'agent")], default='proposed', max_length=12)),
                ('decided_by_sub', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.TextField(blank=True)),
                ('refusal_reason_code', models.CharField(blank=True, choices=[('garant_indisponible', 'Cette personne ne peut pas se porter caution en ce moment.'), ('lien_non_etabli', "Le lien de groupe avec cette personne n'a pas pu être établi."), ('piece_manquante', "Les pièces d'identité du garant n'ont pas pu être relevées."), ('montant_inadapte', 'Le montant proposé ne convient pas pour ce dossier.'), ('autre', "Proposition non retenue par l'agence.")], max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_proposals', to='credits.creditapplication')),
                ('guarantee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposal', to='credits.creditguarantee')),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cautions_pressenties', to='accounts.fintechuser')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cautions_proposees', to='accounts.fintechuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='credits_gua_status_6b24b3_idx'), models.Index(fields=['proposed_by', 'status'], name='credits_gua_propose_7882c6_idx'), models.Index(fields=['application', 'status'], name='credits_gua_applica_48ac4b_idx')],
            },
        ),
    ]
