# Generated by Django 5.2.16 on 2026-07-24 12:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0014_guaranteeproposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREDIT_DISBURSED', 'Décaissement de crédit (B1)'), ('CREDIT_PRINCIPAL_REPAID', 'Remboursement — capital (B2)'), ('CREDIT_INTEREST_COLLECTED', 'Remboursement — intérêts (B3)'), ('CREDIT_COMMISSION_COLLECTED', 'Commission (B4)')], db_index=True, max_length=40)),
                ('loan_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('loan_reference', models.CharField(blank=True, db_index=True, max_length=64)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('actor_sub', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('journal_reference', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_events', to='credits.creditapplication')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='credits_cre_event_t_2bb72f_idx'), models.Index(fields=['consumed_at'], name='credits_cre_consume_03c829_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('event_type', 'reference'), name='credits_un_evenement_par_acte')],
            },
        ),
    ]
