# Generated by Django 5.2.16 on 2026-07-24 12:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0015_creditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplication',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='closed_by_sub',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='closure_comment',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ObservationFiliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_chain_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('filiere', models.CharField(blank=True, max_length=100)),
                ('devise', models.CharField(default='USD', max_length=3)),
                ('montant_decaisse', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('quantite_reference', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unite_reference', models.CharField(blank=True, max_length=30)),
                ('couts_modules', models.JSONField(default=dict)),
                ('cout_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('origine_couts', models.CharField(blank=True, max_length=20)),
                ('contributive', models.BooleanField(db_index=True, default=False)),
                ('clos_le', models.DateTimeField()),
                ('clos_par', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='observation_filiere', to='credits.creditapplication')),
                ('referentiel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='credits.referentielfiliere')),
            ],
            options={
                'ordering': ['-clos_le', '-id'],
                'indexes': [models.Index(fields=['referentiel', 'contributive'], name='credits_obs_referen_8f367f_idx')],
            },
        ),
    ]
