# Generated by Django 5.2.16 on 2026-07-13 16:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('equipment', 'Équipement'), ('property', 'Propriété'), ('vehicle', 'Véhicule'), ('other', 'Autre')], default='other', max_length=12)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('free', 'Libre'), ('pledged', 'Nanti')], default='free', max_length=10)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='accounts.fintechuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
