# Generated by Django 5.2.16 on 2026-07-20 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('assets', '0001_initial'),
        ('credits', '0006_alter_analysisrule_id_alter_linefinding_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='asset',
            name='gage_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_gages', to='credits.creditapplication'),
        ),
        migrations.AddField(
            model_name='asset',
            name='localisation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='asset',
            name='motif_rejet',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='valeur_retenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='verifie_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='verifie_par_sub',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('declare', 'Déclaré'), ('verifie', 'Vérifié'), ('rejete', 'Rejeté'), ('gage', 'Gagé'), ('libere', 'Libéré')], default='declare', max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('materiel', 'Matériel / Équipement'), ('foncier', 'Foncier / Immobilier'), ('vehicule', 'Véhicule'), ('stock', 'Stock / Récolte'), ('autre', 'Autre (non gageable)')], default='autre', max_length=12),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['user', 'status'], name='assets_asse_user_id_698b0a_idx'),
        ),
    ]
