# Generated by Django 5.2.16 on 2026-07-15 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('metric', models.CharField(choices=[('AGENCY_SUSPENDED', 'Agence suspendue depuis'), ('RECONCILIATION_OVERDUE', 'Rapprochement ouvert depuis'), ('COMPLIANCE_SCORE_LOW', 'Score de conformité global'), ('TRANSACTION_OVERDUE', 'Transactions en attente en retard'), ('PARTNER_FAILURES', "Échecs consécutifs d'un partenaire")], max_length=30)),
                ('operator', models.CharField(choices=[('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<=')], max_length=2)),
                ('threshold', models.FloatField()),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Avertissement'), ('CRITICAL', 'Critique')], max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Avertissement'), ('CRITICAL', 'Critique')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('source_type', models.CharField(blank=True, max_length=40)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('dedup_key', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acquittée'), ('RESOLVED', 'Résolue')], default='ACTIVE', max_length=12)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=255)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='alerts.alertrule')),
            ],
            options={
                'ordering': ['-triggered_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('dedup_key',), name='unique_active_alert_dedup_key')],
            },
        ),
    ]
