# Generated by Django 5.2.16 on 2026-07-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_seed_default_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='metric',
            field=models.CharField(choices=[('AGENCY_SUSPENDED', 'Agence suspendue depuis'), ('RECONCILIATION_OVERDUE', 'Rapprochement ouvert depuis'), ('COMPLIANCE_SCORE_LOW', 'Score de conformité global'), ('TRANSACTION_OVERDUE', 'Transactions en attente en retard'), ('PARTNER_FAILURES', "Échecs consécutifs d'un partenaire"), ('TICKET_SLA_BREACHED', 'Tickets en dépassement de SLA')], max_length=30),
        ),
    ]
