# Generated by Django 5.2.16 on 2026-07-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_seed_ticket_sla_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='notify_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
