# Generated by Django 5.2.16 on 2026-07-13 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('actif', 'Actif'), ('cloture', 'Clôturé')], default='en_attente', max_length=10)),
                ('signature', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounts.fintechuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
