# Generated by Django 5.2.16 on 2026-07-22 10:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventEntryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('journal', models.CharField(choices=[('JCR', 'Journal crédit'), ('JEP', 'Journal épargne'), ('JCA', 'Journal caisse'), ('JMM', 'Journal mobile money'), ('JFX', 'Journal change'), ('JIN', 'Journal investissement'), ('JOD', 'Journal opérations diverses')], max_length=3)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "schéma d'écriture",
                'verbose_name_plural': "schémas d'écriture",
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('racine', models.CharField(db_index=True, max_length=24)),
                ('intitule', models.CharField(max_length=200)),
                ('classe', models.PositiveSmallIntegerField()),
                ('nature', models.CharField(choices=[('ACTIF', 'Actif'), ('PASSIF', 'Passif'), ('CHARGE', 'Charge'), ('PRODUIT', 'Produit')], max_length=8)),
                ('devise', models.CharField(blank=True, choices=[('FC', 'Franc congolais'), ('USD', 'Dollar américain')], max_length=3)),
                ('est_transitoire', models.BooleanField(default=False, help_text='Compte de passage (581, 588FX) dont le solde doit tendre vers zéro.')),
                ('cantonnement', models.CharField(blank=True, db_index=True, help_text="Référence de l'offre pour les sous-comptes de cantonnement 419-OFF-xxxx.", max_length=64)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enfants', to='accounting.comptecomptable')),
            ],
            options={
                'verbose_name': 'compte comptable',
                'verbose_name_plural': 'comptes comptables',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TauxChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taux', models.DateField(db_index=True)),
                ('usage', models.CharField(choices=[('OPERATIONNEL', 'Opérationnel (transactions du jour)'), ('CLOTURE', 'Clôture (arrêté comptable)')], max_length=16)),
                ('devise_base', models.CharField(choices=[('FC', 'Franc congolais'), ('USD', 'Dollar américain')], default='USD', max_length=3)),
                ('devise_contre', models.CharField(choices=[('FC', 'Franc congolais'), ('USD', 'Dollar américain')], default='FC', max_length=3)),
                ('taux', models.DecimalField(decimal_places=6, max_digits=18)),
                ('source', models.CharField(choices=[('BCC', 'Banque Centrale du Congo'), ('INTERNE', 'Décision interne'), ('MARCHE', 'Marché parallèle constaté')], default='BCC', max_length=16)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('saisi_par', models.CharField(blank=True, max_length=255)),
                ('valide_par', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'taux de change',
                'verbose_name_plural': 'taux de change',
                'ordering': ['-date_taux', 'usage'],
                'constraints': [models.UniqueConstraint(fields=('date_taux', 'usage', 'devise_base', 'devise_contre'), name='acc_taux_unique_par_jour_et_usage'), models.CheckConstraint(condition=models.Q(('taux__gt', 0)), name='acc_taux_strictement_positif'), models.CheckConstraint(condition=models.Q(('devise_base', models.F('devise_contre')), _negated=True), name='acc_taux_devises_distinctes')],
            },
        ),
        migrations.CreateModel(
            name='PieceComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('date_operation', models.DateField(db_index=True)),
                ('journal', models.CharField(choices=[('JCR', 'Journal crédit'), ('JEP', 'Journal épargne'), ('JCA', 'Journal caisse'), ('JMM', 'Journal mobile money'), ('JFX', 'Journal change'), ('JIN', 'Journal investissement'), ('JOD', 'Journal opérations diverses')], max_length=3)),
                ('libelle', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée')], default='BROUILLON', max_length=10)),
                ('evenement', models.CharField(blank=True, db_index=True, help_text='Code du schéma du catalogue (B1…B16). Vide = opération diverse (OD).', max_length=16)),
                ('motif', models.TextField(blank=True)),
                ('origine_type', models.CharField(blank=True, max_length=64)),
                ('origine_id', models.CharField(blank=True, max_length=64)),
                ('cree_par', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('valide_par', models.CharField(blank=True, max_length=255)),
                ('valide_le', models.DateTimeField(blank=True, null=True)),
                ('piece_contrepassee', models.ForeignKey(blank=True, help_text="Renseigné sur la pièce INVERSE : désigne la pièce qu'elle annule.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrepassations', to='accounting.piececomptable')),
                ('piece_rectifiee', models.ForeignKey(blank=True, help_text="Renseigné sur la pièce CORRIGÉE : désigne la pièce d'origine erronée.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rectifications', to='accounting.piececomptable')),
                ('taux_change', models.ForeignKey(blank=True, help_text="Taux journalisé — OBLIGATOIRE dès qu'une pièce porte plusieurs devises.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pieces', to='accounting.tauxchange')),
            ],
            options={
                'verbose_name': 'pièce comptable',
                'verbose_name_plural': 'pièces comptables',
                'ordering': ['-date_operation', '-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='EventEntryTemplateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens', models.CharField(choices=[('DEBIT', 'Débit'), ('CREDIT', 'Crédit')], max_length=6)),
                ('compte_racine', models.CharField(max_length=32)),
                ('devise_regle', models.CharField(choices=[('OPERATION', "Devise de l'opération"), ('SOURCE', 'Devise source (change)'), ('CIBLE', 'Devise cible (change)'), ('FC', 'Toujours FC'), ('USD', 'Toujours USD')], default='OPERATION', max_length=12)),
                ('montant_ref', models.CharField(max_length=48)),
                ('condition', models.CharField(blank=True, help_text='Vide = ligne toujours produite. Sinon, produite si la condition est active.', max_length=16)),
                ('libelle', models.CharField(blank=True, max_length=255)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='accounting.evententrytemplate')),
            ],
            options={
                'verbose_name': 'ligne de schéma',
                'verbose_name_plural': 'lignes de schéma',
                'ordering': ['template_id', 'ordre', 'id'],
                'constraints': [models.UniqueConstraint(fields=('template', 'ordre'), name='acc_template_ordre_unique')],
            },
        ),
        migrations.CreateModel(
            name='LigneEcriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devise', models.CharField(choices=[('FC', 'Franc congolais'), ('USD', 'Dollar américain')], max_length=3)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('libelle', models.CharField(blank=True, max_length=255)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='accounting.comptecomptable')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='accounting.piececomptable')),
            ],
            options={
                'verbose_name': "ligne d'écriture",
                'verbose_name_plural': "lignes d'écriture",
                'ordering': ['piece_id', 'ordre', 'id'],
                'indexes': [models.Index(fields=['compte', 'devise'], name='accounting__compte__0a35d0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('debit__gte', 0)), name='acc_ligne_debit_positif'), models.CheckConstraint(condition=models.Q(('credit__gte', 0)), name='acc_ligne_credit_positif'), models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='acc_ligne_pas_debit_et_credit'), models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _connector='OR'), name='acc_ligne_non_nulle')],
            },
        ),
        migrations.AddIndex(
            model_name='piececomptable',
            index=models.Index(fields=['statut', 'date_operation'], name='accounting__statut_3603da_idx'),
        ),
    ]
