# Generated by Django 5.2.16 on 2026-07-22 15:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piececomptable',
            name='saisie_manuelle',
            field=models.BooleanField(default=False, help_text="OD saisie à la main : la validation exige un checker DIFFÉRENT du maker. Les pièces produites par le catalogue (événements métier) ne sont pas concernées — elles n'ont pas d'auteur humain à opposer."),
        ),
        migrations.CreateModel(
            name='ArreteProvision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrete', models.DateField(db_index=True)),
                ('devise', models.CharField(choices=[('FC', 'Franc congolais'), ('USD', 'Dollar américain')], max_length=3)),
                ('provision_requise', models.DecimalField(decimal_places=2, max_digits=20)),
                ('provision_anterieure', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dotation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('reprise', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('encours_portefeuille', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base de calcul : encours classé, issu de `portfolio`.', max_digits=20)),
                ('encours_comptable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Solde 413 + 416 au grand livre à la même date — l'écart est un signal, pas une correction automatique.", max_digits=20)),
                ('nombre_credits', models.PositiveIntegerField(default=0)),
                ('cree_par', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arretes_provision', to='accounting.piececomptable')),
            ],
            options={
                'verbose_name': 'arrêté de provision',
                'verbose_name_plural': 'arrêtés de provision',
                'ordering': ['-date_arrete', 'devise'],
            },
        ),
        migrations.CreateModel(
            name='ClasseRisque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('jours_min', models.PositiveIntegerField(help_text='Borne INCLUSE, en jours de retard.')),
                ('jours_max', models.PositiveIntegerField(blank=True, help_text='Borne INCLUSE. NULL = classe terminale (pas de borne supérieure).', null=True)),
                ('taux_provision', models.DecimalField(decimal_places=4, help_text="Fraction de l'encours à provisionner (0.2500 = 25 %).", max_digits=6)),
                ('en_souffrance', models.BooleanField(default=False, help_text='Classe qui déclenche le déclassement automatique 413 → 416 (schéma B5).')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('modifie_par', models.CharField(blank=True, max_length=255)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'classe de risque (PAR)',
                'verbose_name_plural': 'classes de risque (PAR)',
                'ordering': ['ordre', 'jours_min'],
                'constraints': [models.CheckConstraint(condition=models.Q(('taux_provision__gte', 0), ('taux_provision__lte', 1)), name='acc_classe_taux_entre_0_et_1'), models.CheckConstraint(condition=models.Q(('jours_max__isnull', True), ('jours_max__gte', models.F('jours_min')), _connector='OR'), name='acc_classe_bornes_ordonnees')],
            },
        ),
        migrations.CreateModel(
            name='ClassementCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrete', models.DateField(db_index=True)),
                ('loan_id', models.PositiveIntegerField(db_index=True)),
                ('loan_reference', models.CharField(db_index=True, max_length=64)),
                ('jours_retard', models.PositiveIntegerField(default=0)),
                ('encours', models.DecimalField(decimal_places=2, max_digits=20)),
                ('devise', models.CharField(choices=[('FC', 'Franc congolais'), ('USD', 'Dollar américain')], max_length=3)),
                ('en_souffrance', models.BooleanField(default=False)),
                ('cree_par', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('piece_declassement', models.ForeignKey(blank=True, help_text='Pièce B5 (413 → 416) produite par CET arrêté, le cas échéant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declassements', to='accounting.piececomptable')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classements', to='accounting.classerisque')),
            ],
            options={
                'verbose_name': 'classement de crédit',
                'verbose_name_plural': 'classements de crédit',
                'ordering': ['-date_arrete', 'loan_reference'],
            },
        ),
        migrations.CreateModel(
            name='DemandeCompteComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('racine', models.CharField(max_length=24)),
                ('intitule', models.CharField(max_length=200)),
                ('classe', models.PositiveSmallIntegerField()),
                ('nature', models.CharField(choices=[('ACTIF', 'Actif'), ('PASSIF', 'Passif'), ('CHARGE', 'Charge'), ('PRODUIT', 'Produit')], max_length=8)),
                ('devise', models.CharField(blank=True, choices=[('FC', 'Franc congolais'), ('USD', 'Dollar américain')], max_length=3)),
                ('est_transitoire', models.BooleanField(default=False)),
                ('cantonnement', models.CharField(blank=True, max_length=64)),
                ('parent_code', models.CharField(blank=True, max_length=32)),
                ('justification', models.TextField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=12)),
                ('demande_par', models.CharField(max_length=255)),
                ('demande_le', models.DateTimeField(auto_now_add=True)),
                ('decide_par', models.CharField(blank=True, max_length=255)),
                ('decide_le', models.DateTimeField(blank=True, null=True)),
                ('motif_decision', models.TextField(blank=True)),
                ('compte', models.ForeignKey(blank=True, help_text="Renseigné à l'approbation : le compte réellement créé.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='accounting.comptecomptable')),
            ],
            options={
                'verbose_name': "demande d'ouverture de compte",
                'verbose_name_plural': "demandes d'ouverture de compte",
                'ordering': ['-demande_le'],
            },
        ),
        migrations.CreateModel(
            name='LigneArreteProvision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_credits', models.PositiveIntegerField(default=0)),
                ('encours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('taux_applique', models.DecimalField(decimal_places=4, max_digits=6)),
                ('provision', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('arrete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='accounting.arreteprovision')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_arrete', to='accounting.classerisque')),
            ],
            options={
                'verbose_name': "ligne d'arrêté de provision",
                'verbose_name_plural': "lignes d'arrêté de provision",
                'ordering': ['arrete_id', 'classe__ordre'],
            },
        ),
        migrations.AddConstraint(
            model_name='arreteprovision',
            constraint=models.UniqueConstraint(fields=('date_arrete', 'devise'), name='acc_un_arrete_par_date_et_devise'),
        ),
        migrations.AddConstraint(
            model_name='arreteprovision',
            constraint=models.CheckConstraint(condition=models.Q(('dotation__gt', 0), ('reprise__gt', 0), _negated=True), name='acc_arrete_dotation_ou_reprise'),
        ),
        migrations.AddConstraint(
            model_name='classementcredit',
            constraint=models.UniqueConstraint(fields=('date_arrete', 'loan_id'), name='acc_un_classement_par_credit_et_arrete'),
        ),
        migrations.AddConstraint(
            model_name='classementcredit',
            constraint=models.CheckConstraint(condition=models.Q(('encours__gte', 0)), name='acc_classement_encours_positif'),
        ),
        migrations.AddConstraint(
            model_name='demandecomptecomptable',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'EN_ATTENTE')), fields=('code',), name='acc_une_seule_demande_en_attente_par_code'),
        ),
        migrations.AddConstraint(
            model_name='lignearreteprovision',
            constraint=models.UniqueConstraint(fields=('arrete', 'classe'), name='acc_une_ligne_par_classe_et_arrete'),
        ),
    ]
