# Generated by Django 5.2.16 on 2026-07-24 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_piececomptable_saisie_manuelle_arreteprovision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classementcredit',
            name='piece_reclassement',
            field=models.ForeignKey(blank=True, help_text="Pièce B17 (416 → 413) produite par CET arrêté quand le crédit revient à bonne fin. Champ distinct du déclassement : les deux mouvements sont des événements économiques opposés, pas une correction l'un de l'autre.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reclassements', to='accounting.piececomptable'),
        ),
        migrations.CreateModel(
            name='RegleConsommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, help_text='Modèle producteur des événements (ex. « investments.InvestmentEvent »).', max_length=64)),
                ('type_evenement', models.CharField(db_index=True, max_length=48)),
                ('mode', models.CharField(choices=[('PIECE', 'Pièce nouvelle depuis un schéma du catalogue'), ('CONTREPASSATION', "Contrepassation de la pièce d'origine"), ('SANS_ECRITURE', "Aucune écriture définie par l'annexe B")], default='PIECE', max_length=16)),
                ('schema', models.CharField(blank=True, help_text='Code du schéma du catalogue appliqué en mode PIECE (B10, B11…).', max_length=16)),
                ('evenement_origine', models.CharField(blank=True, help_text="Mode CONTREPASSATION : type de l'événement dont la pièce est annulée.", max_length=48)),
                ('compte_tresorerie', models.CharField(blank=True, help_text="Racine du compte résolvant $TRESORERIE (501/511/53x). Un événement peut l'écraser via « compteTresorerie » dans son payload.", max_length=32)),
                ('note', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('modifie_par', models.CharField(blank=True, max_length=255)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "règle de consommation d'événement",
                'verbose_name_plural': "règles de consommation d'événement",
                'ordering': ['source', 'type_evenement'],
                'constraints': [models.UniqueConstraint(fields=('source', 'type_evenement'), name='acc_une_regle_par_type_evenement')],
            },
        ),
    ]
