# Generated by Django 5.2.16 on 2026-07-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_classementcredit_piece_reclassement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceEvenements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text="Identifiant de la file, tel qu'écrit dans « RegleConsommation.source » (convention : « app_label.ModelName »).", max_length=64, unique=True)),
                ('modele', models.CharField(blank=True, help_text="Modèle Django réellement lu (« app_label.ModelName »). Vide = le code fait foi. Distinct du code pour qu'une file puisse être renommée, ou qu'un banc d'essai pointe une file existante sans usurper son identité.", max_length=64)),
                ('libelle', models.CharField(blank=True, max_length=200)),
                ('prefixe_reference', models.CharField(help_text='Préfixe des références de pièce produites depuis cette file (INV, CRE…). Il rend la référence unique entre files : deux événements de deux files peuvent porter le même identifiant.', max_length=8)),
                ('note', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True, help_text="Désactivée, la file cesse d'être consommée et ses événements s'accumulent — ils ne se perdent pas et ne s'écrivent pas de travers.")),
                ('modifie_par', models.CharField(blank=True, max_length=255)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "source d'événements métier",
                'verbose_name_plural': "sources d'événements métier",
                'ordering': ['code'],
            },
        ),
    ]
