# Generated by Django 5.2.16 on 2026-07-11 16:44

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('operator', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('amount_requested', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('amount_approved', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], default='USD', max_length=3)),
                ('duration_months', models.IntegerField(default=12)),
                ('rate', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('frequency', models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('annual', 'Annuel'), ('bullet', 'In fine (à terme)')], default='monthly', max_length=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('manager', models.CharField(blank=True, max_length=150)),
                ('investor', models.CharField(blank=True, max_length=150)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('EN_TRAITEMENT', 'En traitement'), ('APPROUVE', 'Approuvé'), ('EN_COURS', 'En cours'), ('DEFAUT', 'Défaut'), ('CLOTURE', 'Clôturé'), ('REJETE', 'Rejeté'), ('SUSPENDU', 'Suspendu'), ('BLOQUE', 'Bloqué')], default='EN_TRAITEMENT', max_length=16)),
                ('score', models.IntegerField(default=0)),
                ('guarantee', models.CharField(blank=True, max_length=200)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='credits.creditapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanConfigHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('user', models.CharField(blank=True, max_length=120)),
                ('details', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_history', to='portfolio.loan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=120)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='portfolio.loan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('kind', models.CharField(choices=[('DISBURSEMENT', 'Décaissement'), ('REPAYMENT', 'Remboursement'), ('FEE', 'Frais'), ('REMINDER', 'Relance'), ('ADJUSTMENT', 'Ajustement'), ('OTHER', 'Autre')], default='OTHER', max_length=16)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], default='USD', max_length=3)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('original_currency', models.CharField(blank=True, max_length=3)),
                ('payment_method', models.CharField(blank=True, max_length=80)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('VALIDE', 'Validé'), ('EN_ATTENTE', 'En attente'), ('NON_APPLICABLE', 'Non applicable')], default='VALIDE', max_length=16)),
                ('verified_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.loan')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
