# Generated by Django 5.2.16 on 2026-07-15 12:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='borrower_sub',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name='LoanGuarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_items', to='portfolio.loan')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LoanSubWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subwallets', to='portfolio.loan')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='subwallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='portfolio.loansubwallet'),
        ),
        migrations.AddConstraint(
            model_name='loansubwallet',
            constraint=models.UniqueConstraint(fields=('loan', 'module_key'), name='unique_loan_subwallet_module'),
        ),
        migrations.AddConstraint(
            model_name='loansubwallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='subwallet_balance_gte_0'),
        ),
    ]
