"""Le taux du prêt porte enfin son unité.

`Loan.rate` est MENSUEL, le moteur d'analyse raisonne en ANNUEL, et rien ne
distinguait les deux : un « 18 % » de dossier scoré reporté tel quel donnait un prêt
à 216 %/an. On ajoute `annual_rate` (même unité et même précision que
`credits.AnalyseCredit.taux_annuel`) et on élargit `rate` à 6 décimales — 3 ne
suffisaient pas pour 22,6 %/an ÷ 12 = 1,883333…%/mois.

La reprise ci-dessous est une PROJECTION, pas une correction : `annual_rate` reçoit
`rate × 12`, c'est-à-dire ce que le champ mensuel signifie aujourd'hui. Un dossier
hérité dont le taux mensuel vaut 18 se lira donc 216 %/an — c'est le but : rendre
visible un taux qui l'était déjà, jamais le réécrire en silence (principe 3).
"""
# Generated by Django 5.2.16 on 2026-07-24 12:03

from decimal import Decimal, ROUND_HALF_UP
from django.db import migrations, models

MOIS_PAR_AN = Decimal("12")
MILLIEME = Decimal("0.001")


def projeter_le_taux_annuel(apps, schema_editor):
    Loan = apps.get_model("portfolio", "Loan")
    for loan in Loan.objects.filter(annual_rate__isnull=True).iterator():
        loan.annual_rate = (Decimal(loan.rate or 0) * MOIS_PAR_AN).quantize(
            MILLIEME, rounding=ROUND_HALF_UP)
        loan.save(update_fields=["annual_rate"])


def oublier_le_taux_annuel(apps, schema_editor):
    """Réversible : la colonne annuelle n'est qu'une projection du champ mensuel,
    qui reste la donnée d'origine — rien n'est perdu au retour arrière."""
    Loan = apps.get_model("portfolio", "Loan")
    Loan.objects.update(annual_rate=None)


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_loan_borrower_sub_loanguarantee_loansubwallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='annual_rate',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Taux nominal ANNUEL en points de % (18 = 18 %/an). Recopié de l'analyse au rattachement du dossier.", max_digits=6, null=True, verbose_name='Taux ANNUEL (%/an)'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Taux MENSUEL en points de % (1.5 = 1,5 %/mois = 18 %/an). Pour saisir un taux annuel, utilisez « Taux annuel ».', max_digits=9, verbose_name='Taux MENSUEL (%/mois)'),
        ),
        migrations.RunPython(projeter_le_taux_annuel, oublier_le_taux_annuel),
    ]
