# Generated by Django 5.2.16 on 2026-07-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_loan_annual_rate_alter_loan_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='deferral_mode',
            field=models.CharField(choices=[('interets_seuls', 'Intérêts seuls'), ('franchise_totale', 'Franchise totale')], default='interets_seuls', help_text="Intérêts seuls : le client paie les intérêts, le capital reste intact. Franchise totale : rien n'est payé, les intérêts sont capitalisés et grossissent le capital à amortir.", max_length=20, verbose_name='Mode de différé'),
        ),
        migrations.AddField(
            model_name='loan',
            name='deferral_months',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de mois de différé, INCLUS dans la durée totale. Périodicité mensuelle uniquement.', verbose_name='Différé (mois)'),
        ),
    ]
