# Generated by Django 5.2.16 on 2026-07-22 11:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('COUPON', 'Coupon / rendement'), ('CAPITAL', 'Remboursement de capital'), ('REFUND', 'Remboursement de souscription')], default='COUPON', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('value_date', models.DateField()),
                ('executed_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-value_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DistributionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=9)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentCommitteeVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_sub', models.CharField(max_length=255)),
                ('decision', models.CharField(choices=[('approve', "Pour l'approbation"), ('reject', 'Pour le rejet')], max_length=10)),
                ('comment', models.TextField()),
                ('conditions', models.TextField(blank=True)),
                ('quorum_at_vote', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('committee_quorum', models.PositiveIntegerField(blank=True, null=True)),
                ('health_coeff_default', models.DecimalField(decimal_places=3, default=Decimal('4'), max_digits=6)),
                ('health_coeff_concentration', models.DecimalField(decimal_places=3, default=Decimal('50'), max_digits=6)),
                ('health_coeff_late', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=6)),
                ('concentration_threshold', models.DecimalField(decimal_places=4, default=Decimal('0.25'), max_digits=5)),
                ('default_rate_alert', models.DecimalField(decimal_places=4, default=Decimal('0.05'), max_digits=5)),
                ('default_oversubscription_policy', models.CharField(default='QUEUE', max_length=10)),
                ('default_min_funding_ratio', models.DecimalField(decimal_places=4, default=Decimal('0.7000'), max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration investissement',
            },
        ),
        migrations.CreateModel(
            name='InvestmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SUBSCRIPTION_SETTLED', 'Encaissement souscription (B10)'), ('SUBSCRIPTION_REFUNDED', 'Remboursement souscription (B10 contrepassé)'), ('PROJECT_DISBURSED', 'Décaissement projet (B11)'), ('PROJECT_RETURN_RECEIVED', 'Encaissement retour projet (B12)'), ('DISTRIBUTION_PAID', 'Distribution investisseur (B13)'), ('PROJECT_DEFAULTED', 'Défaut projet (provision à constituer)')], db_index=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('segregation_account', models.CharField(blank=True, max_length=32)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('actor_sub', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('journal_reference', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=3)),
                ('to_status', models.CharField(max_length=3)),
                ('actor_sub', models.CharField(blank=True, max_length=255)),
                ('actor_role', models.CharField(blank=True, max_length=64)),
                ('reason', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='offer',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='min_funding_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AddField(
            model_name='offer',
            name='oversubscription_policy',
            field=models.CharField(choices=[('QUEUE', "File d'attente (premier arrivé)"), ('PRORATA', 'Prorata à la clôture'), ('REJECT', "Refus au-delà de l'objectif")], default='QUEUE', max_length=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='reserved_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AddField(
            model_name='offer',
            name='subscription_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='committee_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='conditions_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='defaulted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='disbursed_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AddField(
            model_name='project',
            name='distributed_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AddField(
            model_name='project',
            name='returned_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AddField(
            model_name='subscription',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AddField(
            model_name='subscription',
            name='queue_rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AddField(
            model_name='subscription',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='settled_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AddField(
            model_name='subscription',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicalanalysis',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicalanalysis',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movement',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'Dépôt'), ('SUBSCRIPTION', 'Souscription (réservation)'), ('SETTLEMENT', 'Encaissement souscription'), ('REFUND', 'Remboursement souscription'), ('DISBURSEMENT', 'Décaissement projet'), ('PROJECT_RETURN', 'Encaissement retour projet'), ('DISTRIBUTION', 'Distribution investisseurs'), ('COUPON_REPAYMENT', 'Remboursement coupon'), ('CAPITAL_REPAYMENT', 'Remboursement capital'), ('WITHDRAWAL', 'Retrait'), ('FEES', 'Frais')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Réservée (non encaissée)'), ('WAITLISTED', "Liste d'attente"), ('SETTLED', 'Encaissée'), ('PENDING', 'En attente (hérité)'), ('ACTIVE', 'Actif'), ('REPAYMENT', 'Remboursement'), ('COMPLETED', 'Terminé'), ('DEFAULTED', 'Défaut'), ('REFUNDED', 'Remboursée'), ('CANCELLED', 'Annulé')], default='RESERVED', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('settled_amount__gte', 0), ('allocated_amount__gte', 0), ('refunded_amount__gte', 0)), name='subscription_lifecycle_amounts_nonneg'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='investments.offer'),
        ),
        migrations.AddField(
            model_name='distributionline',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='investments.distribution'),
        ),
        migrations.AddField(
            model_name='distributionline',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_lines', to='investments.investor'),
        ),
        migrations.AddField(
            model_name='distributionline',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_lines', to='investments.subscription'),
        ),
        migrations.AddField(
            model_name='investmentcommitteevote',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_votes', to='investments.project'),
        ),
        migrations.AddField(
            model_name='investmentevent',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_events', to='investments.investor'),
        ),
        migrations.AddField(
            model_name='investmentevent',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_events', to='investments.offer'),
        ),
        migrations.AddField(
            model_name='investmentevent',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_events', to='investments.project'),
        ),
        migrations.AddField(
            model_name='investmentevent',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_events', to='investments.subscription'),
        ),
        migrations.AddField(
            model_name='projecttransition',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='investments.project'),
        ),
        migrations.AddConstraint(
            model_name='distributionline',
            constraint=models.UniqueConstraint(fields=('distribution', 'subscription'), name='unique_distribution_line_per_subscription'),
        ),
        migrations.AddIndex(
            model_name='investmentcommitteevote',
            index=models.Index(fields=['project', 'created_at'], name='investments_project_6d3678_idx'),
        ),
        migrations.AddConstraint(
            model_name='investmentcommitteevote',
            constraint=models.UniqueConstraint(fields=('project', 'voter_sub'), name='unique_investment_committee_vote_per_member'),
        ),
        migrations.AddIndex(
            model_name='investmentevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='investments_event_t_cdd8c3_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentevent',
            index=models.Index(fields=['consumed_at'], name='investments_consume_64b796_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttransition',
            index=models.Index(fields=['project', 'created_at'], name='investments_project_bc4cd2_idx'),
        ),
    ]
