# Generated by Django 5.2.16 on 2026-07-22 14:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_distribution_distributionline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentconfig',
            name='expert_valuation_max_age_months',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='investmentconfig',
            name='p12_provision_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5),
        ),
        migrations.AddField(
            model_name='project',
            name='expert_valuation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='expert_valuation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='expert_valuation_source',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
