# Generated by Django 5.2.16 on 2026-07-22 16:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_investmentconfig_expert_valuation_max_age_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentconfig',
            name='performance_deviation_alert_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='performancereport',
            name='cost_deviation_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='performancereport',
            name='production_deviation_percent',
            field=models.FloatField(default=0),
        ),
    ]
