# Generated by Django 5.2.16 on 2026-07-24 12:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_obligationposition_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repaymentschedule',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AddConstraint(
            model_name='repaymentschedule',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='repayment_schedule_amount_paid_nonneg'),
        ),
    ]
