# Generated by Django 5.2.16 on 2026-07-24 12:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_repaymentschedule_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialanalysis',
            name='dscr',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='financialanalysis',
            name='ebitda_margin',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='financialanalysis',
            name='irr',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='actual_costs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='actual_production',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='actual_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='cost_deviation_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='deviation_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='forecast_costs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='forecast_production',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='forecast_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='production_deviation_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
