# Generated by Django 5.2.16 on 2026-07-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('global_score', models.FloatField()),
                ('components', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
    ]
