from django.urls import path

from . import views

urlpatterns = [
    path("projects", views.projects),
    path("projects/<str:code>", views.project_detail),
    path("projects/<str:code>/action", views.project_action),
    path("projects/<str:code>/transitions", views.project_transitions),
    path("projects/<str:code>/committee-votes", views.project_committee_votes),
    path("projects/<str:code>/approve-analysis", views.project_analysis_approve),
    path("projects/<str:code>/clear-conditions", views.project_clear_conditions),
    path("projects/<str:code>/expert-valuation", views.project_expert_valuation),
    path("projects/<str:code>/close-fundraising", views.project_close_fundraising),
    path("projects/<str:code>/disburse", views.project_disburse),
    path("projects/<str:code>/record-return", views.project_record_return),
    path("projects/<str:code>/cancel", views.project_cancel),
    path("projects/<str:code>/technical-analysis", views.project_technical_analysis),
    path("projects/<str:code>/financial-analysis", views.project_financial_analysis),
    path("offers", views.offers),
    path("offers/open", views.offers_open),
    path("offers/<int:offer_id>/close", views.offer_close),
    path("offers/<int:offer_id>/distribute", views.offer_distribute),
    path("offers/<int:offer_id>/collateral", views.offer_collateral),
    path("investors", views.investors),
    path("investors/me", views.my_investor_profile),
    path("investors/<int:investor_id>/action", views.investor_action),
    path("subscriptions", views.subscriptions),
    path("subscriptions/mine", views.my_subscriptions),
    path("subscriptions/<int:subscription_id>/settle", views.subscription_settle),
    path("subscriptions/<int:subscription_id>/cancel", views.subscription_cancel),
    path("movements", views.movements),
    path("schedules", views.schedules),
    path("sub-portfolios", views.sub_portfolios),
    path("observations", views.observations),
    path("questions", views.questions),
    path("questions/<int:question_id>/answer", views.question_answer),
    path("performance-reports", views.performance_reports),
    path("obligations", views.obligations),
    path("obligations/<int:position_id>/withdraw", views.obligation_withdraw),
    path("obligations/<int:position_id>/convert", views.obligation_convert),
    path("obligations/<int:position_id>/withdrawals", views.obligation_withdrawals),
    path("obligations/<int:position_id>/conversions", views.obligation_conversions),
    path("secondary-market", views.secondary_market),
    path("dashboard-metrics", views.dashboard_metrics),
    path("portfolio-allocation", views.my_portfolio_allocation),
    path("metrics/mine", views.my_metrics),
    path("metrics/portfolio", views.portfolio_metrics),
    path("pipeline", views.pipeline),
    path("accounting-events", views.accounting_events),
]
