# Generated by Django 5.2.16 on 2026-07-10 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='datasources/')),
                ('original_name', models.CharField(max_length=255)),
                ('dataset_key', models.CharField(db_index=True, max_length=255)),
                ('kind', models.CharField(choices=[('REFERENTIEL', 'REFERENTIEL'), ('SIMULATEUR', 'SIMULATEUR'), ('ANNEXE', 'ANNEXE'), ('AUTRE', 'AUTRE')], default='AUTRE', max_length=20)),
                ('status', models.CharField(choices=[('STAGED', 'STAGED'), ('COMMITTED', 'COMMITTED')], default='STAGED', max_length=12)),
                ('revision', models.IntegerField(default=1)),
                ('is_current', models.BooleanField(default=False)),
                ('uploaded_by', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('committed_by', models.CharField(blank=True, max_length=255)),
                ('preview', models.JSONField(blank=True, default=dict)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='dataio.datasource')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.IntegerField(default=0)),
                ('n_rows', models.IntegerField(default=0)),
                ('n_cols', models.IntegerField(default=0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='dataio.datasource')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('source', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DataColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('dtype', models.CharField(default='text', max_length=12)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='dataio.datatable')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField()),
                ('values', models.JSONField(default=dict)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dataio.datatable')),
            ],
            options={
                'ordering': ['row_index'],
                'indexes': [models.Index(fields=['table', 'row_index'], name='dataio_data_table_i_5873a1_idx')],
            },
        ),
    ]
