# Generated by Django 5.2.16 on 2026-07-20 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0008_creditapplication_needs_source'),
        ('dataio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='credit_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='needs_sources', to='credits.creditapplication'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='kind',
            field=models.CharField(choices=[('REFERENTIEL', 'REFERENTIEL'), ('SIMULATEUR', 'SIMULATEUR'), ('ANNEXE', 'ANNEXE'), ('FEUILLE_BESOINS', 'FEUILLE_BESOINS'), ('AUTRE', 'AUTRE')], default='AUTRE', max_length=20),
        ),
    ]
