# Generated by Django 5.2.16 on 2026-07-21 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataio', '0002_datasource_credit_application_datasource_sha256_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, default='FEUILLE_BESOINS', max_length=40)),
                ('file', models.FileField(upload_to='dataio/templates/')),
                ('original_name', models.CharField(max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', "En attente d'activation"), ('active', 'Actif'), ('archived', 'Archivé')], db_index=True, default='pending', max_length=12)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('uploaded_by', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activated_by', models.CharField(blank=True, max_length=255)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='dataio.filetemplate')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['kind', 'status'], name='dataio_file_kind_4e1a5c_idx')],
            },
        ),
    ]
