# Generated by Django 5.2.16 on 2026-07-10 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferentielVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceWorkbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='referentiels/')),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_by', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_ok', models.BooleanField(default=False)),
                ('parse_log', models.TextField(blank=True)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workbooks', to='referentiel.referentielversion')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('seuil_dscr', models.FloatField(default=1.2)),
                ('seuil_dscr_stresse', models.FloatField(default=1.0)),
                ('couverture_min', models.FloatField(default=1.0)),
                ('score_global_min', models.FloatField(default=70.0)),
                ('poids_technique', models.FloatField(default=25.0)),
                ('poids_financier', models.FloatField(default=20.0)),
                ('poids_stress', models.FloatField(default=10.0)),
                ('poids_comportemental', models.FloatField(default=30.0)),
                ('poids_garanties', models.FloatField(default=15.0)),
                ('taux_interet_annuel', models.FloatField(default=0.24)),
                ('frais_dossier', models.FloatField(default=0.02)),
                ('commissions', models.FloatField(default=0.01)),
                ('duree_max_mois', models.IntegerField(default=24)),
                ('plafond_delegue', models.FloatField(default=25000.0)),
                ('decote_garantie', models.FloatField(default=0.3)),
                ('phase_deploiement', models.CharField(default='PHASE_1', max_length=20)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configs', to='referentiel.referentielversion')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_code', models.CharField(max_length=2)),
                ('chain_slug', models.CharField(max_length=40)),
                ('chain_libelle', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('systeme', models.CharField(blank=True, max_length=160)),
                ('cycle_months', models.FloatField(blank=True, null=True)),
                ('parametre_cle', models.CharField(blank=True, max_length=160)),
                ('unite', models.CharField(blank=True, max_length=60)),
                ('rendement_min', models.FloatField(blank=True, null=True)),
                ('rendement_max', models.FloatField(blank=True, null=True)),
                ('cout_text', models.CharField(blank=True, max_length=120)),
                ('cout_min', models.FloatField(blank=True, null=True)),
                ('cout_max', models.FloatField(blank=True, null=True)),
                ('prix_text', models.CharField(blank=True, max_length=120)),
                ('prix_min', models.FloatField(blank=True, null=True)),
                ('prix_max', models.FloatField(blank=True, null=True)),
                ('perte_text', models.CharField(blank=True, max_length=120)),
                ('perte_max', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, max_length=60)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('date_maj', models.CharField(blank=True, max_length=40)),
                ('zone', models.CharField(blank=True, max_length=200)),
                ('observations', models.TextField(blank=True)),
                ('columns', models.JSONField(blank=True, default=dict)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='referentiel.referentielversion')),
            ],
            options={
                'ordering': ['chain_code', 'name'],
                'indexes': [models.Index(fields=['version', 'chain_code'], name='referentiel_version_366a98_idx')],
            },
        ),
    ]
