# Generated by Django 5.2.16 on 2026-07-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionconfig',
            name='caution_consent_window_hours',
            field=models.IntegerField(default=72),
        ),
        migrations.AddField(
            model_name='institutionconfig',
            name='caution_max_actives',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='institutionconfig',
            name='caution_ratio_epargne',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='institutionconfig',
            name='decote_caution_morale',
            field=models.FloatField(default=0.7),
        ),
    ]
