# Generated by Django 5.2.16 on 2026-07-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_staffprofile_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Suspendu', 'Suspendu')], default='Actif', max_length=10),
        ),
    ]
