# Generated by Django 5.2.16 on 2026-07-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_staffprofile_last_login_at_staffprofile_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleOverride',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('level', models.IntegerField(default=0)),
                ('type', models.CharField(default='Gestion', max_length=40)),
                ('read', models.BooleanField(default=True)),
                ('create', models.BooleanField(default=False)),
                ('validate', models.BooleanField(default=False)),
                ('disburse', models.BooleanField(default=False)),
                ('audit', models.BooleanField(default=False)),
                ('config', models.BooleanField(default=False)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('mfa_step_up_required', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='view_override',
            field=models.CharField(blank=True, choices=[('client', 'client'), ('investor', 'investor'), ('admin', 'admin'), ('comptable', 'comptable'), ('caissier', 'caissier'), ('auditeur', 'auditeur')], max_length=20),
        ),
    ]
