# Generated by Django 5.2.16 on 2026-07-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_roleoverride_staffprofile_view_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='per_operation_ceiling',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
