# Generated by Django 5.2.16 on 2026-07-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_staffprofile_per_operation_ceiling'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleoverride',
            name='cooperatives',
            field=models.BooleanField(default=False),
        ),
    ]
