# Generated by Django 5.2.16 on 2026-07-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('Connecté', 'Connecté'), ('Actif', 'Actif'), ('En attente', 'En attente'), ('Déconnecté', 'Déconnecté')], default='En attente', max_length=12)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
