# Generated by Django 5.2.16 on 2026-07-15 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='base_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='partner',
            name='circuit_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='circuit_state',
            field=models.CharField(choices=[('CLOSED', 'Fermé'), ('OPEN', 'Ouvert'), ('HALF_OPEN', 'Semi-ouvert')], default='CLOSED', max_length=10),
        ),
        migrations.AddField(
            model_name='partner',
            name='consecutive_failures',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PartnerHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('ok', models.BooleanField()),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('error_text', models.CharField(blank=True, max_length=255)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='partners.partner')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Succès'), ('FAILED', 'Échec')], max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('error_text', models.CharField(blank=True, max_length=255)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='partners.partner')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
