# Generated by Django 5.2.16 on 2026-07-13 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_sub', models.CharField(max_length=255)),
                ('manager_sub', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('investor_sub', 'manager_sub'), name='unique_conversation')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_sub', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('credit', 'Crédit'), ('epargne', 'Épargne'), ('mobile-money', 'Mobile Money'), ('comptabilite', 'Comptabilité'), ('fx', 'Change (FX)'), ('technique', 'Technique')], default='technique', max_length=14)),
                ('priority', models.CharField(choices=[('faible', 'Faible'), ('normal', 'Normal'), ('urgent', 'Urgent'), ('critique', 'Critique')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('ouvert', 'Ouvert'), ('en-traitement', 'En traitement'), ('escalade', 'Escaladé'), ('resolu', 'Résolu'), ('rejete', 'Rejeté')], default='ouvert', max_length=14)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.fintechuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
