# Generated by Django 5.2.16 on 2026-07-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_ticket_assigned_to_sub_ticket_level_ticketmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rejected_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reopened_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='satisfaction_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='satisfaction_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_breached_first_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_breached_resolution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_first_response_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_resolution_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='waiting_on',
            field=models.CharField(choices=[('agent', 'Agent'), ('client', 'Client')], default='agent', max_length=10),
        ),
    ]
