# Generated by Django 5.2.16 on 2026-07-17 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_ticket_first_response_at_ticket_rejected_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_team',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='original_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='support.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reject_type',
            field=models.CharField(blank=True, choices=[('doublon', 'Doublon'), ('hors_perimetre', 'Hors périmètre'), ('informations_insuffisantes', 'Informations insuffisantes'), ('fraude_suspectee', 'Fraude suspectée')], max_length=30),
        ),
        migrations.CreateModel(
            name='MobileMoneyVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('airtel', 'Airtel Money'), ('orange', 'Orange Money'), ('mpesa', 'M-Pesa')], max_length=10)),
                ('transaction_ref', models.CharField(max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='CDF', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('found_operator_side', "Trouvée chez l'opérateur"), ('not_found', 'Introuvable'), ('already_credited', 'Déjà créditée'), ('failed', 'Échec API')], default='pending', max_length=20)),
                ('raw_response', models.JSONField(default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mm_verifications', to='support.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingFinancialAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(default='force_credit', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=3)),
                ('initiated_by', models.CharField(max_length=255)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending_approval', "En attente d'approbation"), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending_approval', max_length=20)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('accounting_ref', models.CharField(blank=True, max_length=100)),
                ('rejection_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_actions', to='support.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='support.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
