# Generated by Django 5.2.16 on 2026-07-13 16:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('AVEC', 'AVEC'), ('MUTUELLE', 'Mutuelle'), ('COOPERATIVE', 'Coopérative'), ('ORGANISATION_PAYSANNE', 'Organisation paysanne')], default='AVEC', max_length=24)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('rate', models.DecimalField(decimal_places=3, default=Decimal('6.0'), max_digits=5)),
                ('frequency', models.CharField(choices=[('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel')], default='mensuel', max_length=14)),
                ('deposit_mode', models.CharField(choices=[('agent', 'Agent'), ('mobile_money', 'Mobile Money'), ('bank', 'Banque'), ('wallet', 'Portefeuille')], default='agent', max_length=14)),
                ('admin_sub', models.CharField(blank=True, max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupIntegrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_requests', to='accounts.fintechuser')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_requests', to='savings.savingsgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('objective_type', models.CharField(choices=[('investissement', 'Investissement'), ('production', 'Production'), ('transformation', 'Transformation'), ('commercialisation', 'Commercialisation'), ('reserves', 'Réserves'), ('actions', 'Actions'), ('immobilier', 'Immobilier'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('plan_type', models.CharField(choices=[('campagne', 'Campagne (4.5%)'), ('equipement', 'Équipement (3.8%)'), ('groupee', 'Groupée (5.2%)')], default='campagne', max_length=12)),
                ('objectif', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('cloture', 'Clôturé')], default='actif', max_length=10)),
                ('interest_rate', models.DecimalField(decimal_places=3, default=Decimal('4.5'), max_digits=5)),
                ('accrued_interest', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('deposit_channel', models.CharField(choices=[('agent', 'Agent'), ('mobile_money', 'Mobile Money'), ('bank', 'Banque'), ('wallet', 'Portefeuille')], default='agent', max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_plans', to='accounts.fintechuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('channel', models.CharField(choices=[('agent', 'Agent'), ('mobile_money', 'Mobile Money'), ('bank', 'Banque'), ('wallet', 'Portefeuille')], default='agent', max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='savings.savingsplan')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='savings.savingsgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_groups', to='accounts.fintechuser')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'user'), name='unique_group_member')],
            },
        ),
    ]
