# Generated by Django 5.2.16 on 2026-07-23 10:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsplan',
            name='frequency',
            field=models.CharField(choices=[('hebdomadaire', 'Hebdomadaire'), ('bimensuel', 'Bimensuel'), ('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel')], default='mensuel', max_length=14),
        ),
        migrations.AddField(
            model_name='savingsplan',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.375'), max_digits=6),
        ),
        migrations.AddField(
            model_name='savingsplan',
            name='periodic_deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='savingsplan',
            name='rate_status',
            field=models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('bloque', 'Bloqué')], default='actif', max_length=10),
        ),
        migrations.CreateModel(
            name='SavingsAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('deposit_mode', models.CharField(choices=[('agent', 'Agent'), ('mobile_money', 'Mobile Money'), ('bank', 'Banque'), ('wallet', 'Portefeuille')], default='agent', max_length=14)),
                ('frequency', models.CharField(choices=[('hebdomadaire', 'Hebdomadaire'), ('bimensuel', 'Bimensuel'), ('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel')], default='mensuel', max_length=14)),
                ('periodic_deposit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('actor', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='savings.savingsplan')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SavingsRateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('monthly_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('bloque', 'Bloqué')], max_length=10)),
                ('effective_date', models.DateField()),
                ('action', models.CharField(choices=[('rate_update', 'Modification du taux'), ('block', 'Blocage (taux 0%)'), ('suspend', 'Suspension'), ('resume', 'Réactivation')], default='rate_update', max_length=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('actor', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_changes', to='savings.savingsplan')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
