# Generated by Django 5.2.16 on 2026-07-24 12:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_savingsplan_frequency_savingsplan_monthly_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('channel', models.CharField(choices=[('agent', 'Agent'), ('mobile_money', 'Mobile Money'), ('bank', 'Banque'), ('wallet', 'Portefeuille')], default='agent', max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='savings.savingsplan')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SavingsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SAVINGS_DEPOSITED', "Dépôt d'épargne (B8)"), ('SAVINGS_WITHDRAWN', "Retrait d'épargne (B9)")], db_index=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('actor_sub', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('journal_reference', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_events', to='savings.savingsplan')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='savings_sav_event_t_542ea3_idx'), models.Index(fields=['consumed_at'], name='savings_sav_consume_9b3019_idx')],
            },
        ),
    ]
