# Generated by Django 5.2.16 on 2026-07-13 15:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('class_no', models.IntegerField()),
                ('currencies', models.JSONField(blank=True, default=list)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ledger.chartaccount')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('piece_ref', models.CharField(max_length=64)),
                ('code', models.CharField(choices=[('JCR', 'Journal crédit'), ('JEP', 'Journal épargne'), ('JCA', 'Journal caisse'), ('JMM', 'Journal mobile money'), ('JFX', 'Journal change')], max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('VALIDE', 'Validé'), ('EN_ATTENTE', 'En attente'), ('REJETE', 'Rejeté')], default='VALIDE', max_length=10)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('date', 'piece_ref'), name='journalentry_date_pieceref_unique')],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('user_sub', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ledger.chartaccount')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.journalentry')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('debit__gte', 0)), name='line_debit_nonneg'), models.CheckConstraint(condition=models.Q(('credit__gte', 0)), name='line_credit_nonneg'), models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='line_not_both_debit_credit')],
            },
        ),
    ]
