"""Amorce le plan comptable SYSCOHADA révisé (référence : Acte uniforme OHADA relatif au
droit comptable et à l'information financière, système normal).

Portée retenue (adaptation au métier d'AGRICAP FINTECH, un établissement de microfinance/
crédit bi-monnaie CDF/USD, pas une entreprise commerciale/industrielle) :
  - Classes 1, 4, 5, 6, 7 (ressources durables, tiers, trésorerie, charges, produits) :
    comptes principaux (2 chiffres) ET sous-comptes (3 chiffres) au complet — ce sont les
    classes que le système utilise réellement au quotidien.
  - Classes 2, 3, 8 (actif immobilisé, stocks, autres charges/produits) : comptes
    principaux (2 chiffres) seulement — présents pour la conformité OHADA (toute classe
    1-8 est obligatoire) sans transcrire les centaines de sous-comptes sans objet pour un
    prêteur (cheptel, matériel aérien/naval, stocks de marchandises, etc.) ; un
    sous-compte pourra être ajouté à la main via l'écran Plan Comptable si un besoin réel
    apparaît (ex. achat de matériel informatique).
  - Classe 9 (engagements hors bilan / comptabilité analytique) : non amorcée, la norme la
    qualifie elle-même de facultative et AGRICAP n'a pas de module d'engagements/analytique.

En plus du squelette SYSCOHADA standard, quelques comptes divisionnaires à 4 chiffres
propres à AGRICAP sont ajoutés sous leur parent standard correct (ex. 538 « Autres
organismes financiers » reçoit 5381/5382/5383 pour Airtel Money/Orange Money/M-Pesa) —
remplace l'ancien plan comptable codé en dur du frontend (`ChartOfAccountsViewer.jsx`) qui
utilisait une numérotation non conforme (ex. 50=Caisse, 51=Banques, alors que SYSCOHADA
révisé attribue 52=Banques, 57=Caisse)."""
from __future__ import annotations

from django.db import migrations

# (code, libellé) — un compte principal (2 chiffres) doit précéder ses sous-comptes.
ACCOUNTS: list[tuple[str, str]] = [
    # ------------------------------------------------------------------ CLASSE 1
    ("10", "CAPITAL"),
    ("101", "Capital social"),
    ("102", "Capital par dotation"),
    ("103", "Capital personnel"),
    ("104", "Compte de l'exploitant"),
    ("105", "Primes liées aux capitaux propres"),
    ("106", "Écarts de réévaluation"),
    ("109", "Actionnaires, capital souscrit, non appelé"),
    ("11", "RÉSERVES"),
    ("111", "Réserve légale"),
    ("112", "Réserves statutaires ou contractuelles"),
    ("113", "Réserves réglementées"),
    ("118", "Autres réserves"),
    ("12", "REPORT À NOUVEAU"),
    ("121", "Report à nouveau créditeur"),
    ("129", "Report à nouveau débiteur"),
    ("13", "RÉSULTAT NET DE L'EXERCICE"),
    ("130", "Résultat en instance d'affectation"),
    ("131", "Résultat net : bénéfice"),
    ("132", "Marge brute (M.B.)"),
    ("133", "Valeur ajoutée (V.A.)"),
    ("134", "Excédent brut d'exploitation (E.B.E.)"),
    ("135", "Résultat d'exploitation (R.E.)"),
    ("136", "Résultat financier (R.F.)"),
    ("137", "Résultat des activités ordinaires (R.A.O.)"),
    ("138", "Résultat hors activités ordinaires (R.H.A.O.)"),
    ("139", "Résultat net : perte"),
    ("14", "SUBVENTIONS D'INVESTISSEMENT"),
    ("141", "Subventions d'équipement A"),
    ("142", "Subventions d'équipement B"),
    ("148", "Autres subventions d'investissement"),
    ("15", "PROVISIONS RÉGLEMENTÉES ET FONDS ASSIMILÉS"),
    ("151", "Amortissements dérogatoires"),
    ("152", "Plus-values de cession à réinvestir"),
    ("153", "Fonds réglementés"),
    ("154", "Provision spéciale de réévaluation"),
    ("155", "Provisions réglementées relatives aux immobilisations"),
    ("156", "Provisions réglementées relatives aux stocks"),
    ("157", "Provisions pour investissement"),
    ("158", "Autres provisions et fonds réglementés"),
    ("16", "EMPRUNTS ET DETTES ASSIMILÉES"),
    ("161", "Emprunts obligataires"),
    ("162", "Emprunts et dettes auprès des établissements de crédit"),
    ("163", "Avances reçues de l'État"),
    ("164", "Avances reçues et comptes courants bloqués"),
    ("165", "Dépôts et cautionnements reçus"),
    ("166", "Intérêts courus"),
    ("167", "Avances assorties de conditions particulières"),
    ("168", "Autres emprunts et dettes"),
    ("17", "DETTES DE CRÉDIT-BAIL ET CONTRATS ASSIMILÉS"),
    ("172", "Emprunts équivalents de crédit-bail immobilier"),
    ("173", "Emprunts équivalents de crédit-bail mobilier"),
    ("176", "Intérêts courus"),
    ("178", "Emprunts équivalents d'autres contrats"),
    ("18", "DETTES LIÉES À DES PARTICIPATIONS ET COMPTES DE LIAISON"),
    ("181", "Dettes liées à des participations"),
    ("182", "Dettes liées à des sociétés en participation"),
    ("183", "Intérêts courus sur dettes liées à des participations"),
    ("184", "Comptes permanents bloqués des établissements et succursales"),
    ("185", "Comptes permanents non bloqués des établissements et succursales"),
    ("186", "Comptes de liaison charges"),
    ("187", "Comptes de liaison produits"),
    ("188", "Comptes de liaison des sociétés en participation"),
    ("19", "PROVISIONS FINANCIÈRES POUR RISQUES ET CHARGES"),
    ("191", "Provisions pour litiges"),
    ("192", "Provisions pour garanties données aux clients"),
    ("193", "Provisions pour pertes sur marchés à achèvement futur"),
    ("194", "Provisions pour pertes de change"),
    ("195", "Provisions pour impôts"),
    ("196", "Provisions pour pensions et obligations similaires"),
    ("197", "Provisions pour charges à répartir sur plusieurs exercices"),
    ("198", "Autres provisions financières pour risques et charges"),

    # ------------------------------------------------------- CLASSE 2 (principaux seuls)
    ("20", "CHARGES IMMOBILISÉES"),
    ("21", "IMMOBILISATIONS INCORPORELLES"),
    ("22", "TERRAINS"),
    ("23", "BÂTIMENTS, INSTALLATIONS TECHNIQUES ET AGENCEMENTS"),
    ("24", "MATÉRIEL"),
    ("25", "AVANCES ET ACOMPTES VERSÉS SUR IMMOBILISATIONS"),
    ("26", "TITRES DE PARTICIPATION"),
    ("27", "AUTRES IMMOBILISATIONS FINANCIÈRES"),
    ("28", "AMORTISSEMENTS"),
    ("29", "PROVISIONS POUR DÉPRÉCIATION DES IMMOBILISATIONS"),

    # ------------------------------------------------------- CLASSE 3 (principaux seuls)
    ("31", "MARCHANDISES"),
    ("32", "MATIÈRES PREMIÈRES ET FOURNITURES LIÉES"),
    ("33", "AUTRES APPROVISIONNEMENTS"),
    ("34", "PRODUITS EN COURS"),
    ("35", "SERVICES EN COURS"),
    ("36", "PRODUITS FINIS"),
    ("37", "PRODUITS INTERMÉDIAIRES ET RÉSIDUELS"),
    ("38", "STOCKS EN COURS DE ROUTE, EN CONSIGNATION OU EN DÉPÔT"),
    ("39", "DÉPRÉCIATIONS DES STOCKS"),

    # ------------------------------------------------------------------ CLASSE 4
    ("40", "FOURNISSEURS ET COMPTES RATTACHÉS"),
    ("401", "Fournisseurs, dettes en compte"),
    ("402", "Fournisseurs, effets à payer"),
    ("408", "Fournisseurs, factures non parvenues"),
    ("409", "Fournisseurs débiteurs"),
    ("41", "CLIENTS ET COMPTES RATTACHÉS"),
    ("411", "Clients"),
    ("4111", "Clients — comptes épargne"),
    ("412", "Clients, effets à recevoir en portefeuille"),
    ("4121", "Crédits à court terme"),
    ("414", "Créances sur cessions d'immobilisations"),
    ("415", "Clients, effets escomptés non échus"),
    ("416", "Créances clients litigieuses ou douteuses (crédits en souffrance > 90 jours)"),
    ("418", "Clients, produits à recevoir"),
    ("419", "Clients créditeurs"),
    ("42", "PERSONNEL"),
    ("421", "Personnel, avances et acomptes"),
    ("422", "Personnel, rémunérations dues"),
    ("423", "Personnel, oppositions, saisies-arrêts"),
    ("424", "Personnel, œuvres sociales internes"),
    ("425", "Représentants du personnel"),
    ("426", "Personnel, participation aux bénéfices"),
    ("427", "Personnel — dépôts"),
    ("428", "Personnel, charges à payer et produits à recevoir"),
    ("43", "ORGANISMES SOCIAUX"),
    ("431", "Sécurité sociale"),
    ("432", "Caisses de retraite complémentaire"),
    ("433", "Autres organismes sociaux"),
    ("438", "Organismes sociaux, charges à payer et produits à recevoir"),
    ("44", "ÉTAT ET COLLECTIVITÉS PUBLIQUES"),
    ("441", "État, impôt sur les bénéfices"),
    ("442", "État, autres impôts et taxes"),
    ("443", "État, T.V.A. facturée"),
    ("444", "État, T.V.A. due ou crédit de T.V.A."),
    ("445", "État, T.V.A. récupérable"),
    ("446", "État, autres taxes sur le chiffre d'affaires"),
    ("447", "État, impôts retenus à la source"),
    ("448", "État, charges à payer et produits à recevoir"),
    ("449", "État, créances et dettes diverses"),
    ("45", "ORGANISMES INTERNATIONAUX"),
    ("451", "Opérations avec les organismes africains"),
    ("452", "Opérations avec les autres organismes internationaux"),
    ("458", "Organismes internationaux, fonds de dotation et subventions à recevoir"),
    ("46", "ASSOCIÉS ET GROUPE"),
    ("461", "Associés, opérations sur le capital"),
    ("462", "Associés, comptes courants"),
    ("463", "Associés, opérations faites en commun"),
    ("465", "Associés, dividendes à payer"),
    ("466", "Groupe, comptes courants"),
    ("467", "Actionnaires, restant dû sur capital appelé"),
    ("47", "DÉBITEURS ET CRÉDITEURS DIVERS"),
    ("471", "Comptes d'attente"),
    ("472", "Versements restant à effectuer sur titres non libérés"),
    ("474", "Répartition périodique des charges et des produits"),
    ("475", "Créances sur travaux non encore facturables"),
    ("476", "Charges constatées d'avance"),
    ("477", "Produits constatés d'avance"),
    ("478", "Écarts de conversion — actif"),
    ("479", "Écarts de conversion — passif"),
    ("48", "CRÉANCES ET DETTES HORS ACTIVITÉS ORDINAIRES (H.A.O.)"),
    ("481", "Fournisseurs d'investissements"),
    ("482", "Fournisseurs d'investissements, effets à payer"),
    ("483", "Dettes sur acquisition de titres de placement"),
    ("484", "Autres dettes hors activités ordinaires (H.A.O.)"),
    ("485", "Créances sur cessions d'immobilisations"),
    ("486", "Créances sur cessions de titres de placement"),
    ("488", "Autres créances hors activités ordinaires (H.A.O.)"),
    ("49", "DÉPRÉCIATIONS ET RISQUES PROVISIONNÉS (TIERS)"),
    ("490", "Dépréciations des comptes fournisseurs"),
    ("491", "Dépréciations des comptes clients"),
    ("4911", "Provisions pour risques de crédit (prêts en souffrance)"),
    ("492", "Dépréciations des comptes personnel"),
    ("493", "Dépréciations des comptes organismes sociaux"),
    ("494", "Dépréciations des comptes État et collectivités publiques"),
    ("495", "Dépréciations des comptes organismes internationaux"),
    ("496", "Dépréciations des comptes associés et groupe"),
    ("497", "Dépréciations des comptes débiteurs divers"),
    ("498", "Dépréciations des comptes de créances H.A.O."),
    ("499", "Risques provisionnés"),

    # ------------------------------------------------------------------ CLASSE 5
    ("50", "TITRES DE PLACEMENT"),
    ("501", "Titres du Trésor et bons de caisse à court terme"),
    ("502", "Actions"),
    ("503", "Obligations"),
    ("504", "Bons de souscription"),
    ("505", "Titres négociables hors région"),
    ("506", "Intérêts courus"),
    ("508", "Autres valeurs assimilées"),
    ("51", "VALEURS À ENCAISSER"),
    ("511", "Effets à encaisser"),
    ("512", "Effets à l'encaissement"),
    ("513", "Chèques à encaisser"),
    ("514", "Chèques à l'encaissement"),
    ("515", "Cartes de crédit à encaisser"),
    ("518", "Autres valeurs à l'encaissement"),
    ("52", "BANQUES"),
    ("521", "Banques locales"),
    ("5211", "Banque principale"),
    ("522", "Banques autres États région"),
    ("523", "Banques autres États zone monétaire"),
    ("524", "Banques hors zone monétaire"),
    ("526", "Banques, intérêts courus"),
    ("53", "ÉTABLISSEMENTS FINANCIERS ET ASSIMILÉS"),
    ("531", "Chèques postaux"),
    ("532", "Trésor"),
    ("533", "Sociétés de gestion et d'intermédiation (S.G.I.)"),
    ("536", "Établissements financiers, intérêts courus"),
    ("538", "Autres organismes financiers"),
    ("5381", "Airtel Money"),
    ("5382", "Orange Money"),
    ("5383", "M-Pesa"),
    ("54", "INSTRUMENTS DE TRÉSORERIE"),
    ("541", "Options de taux d'intérêt"),
    ("542", "Options de taux de change"),
    ("543", "Options de taux boursiers"),
    ("544", "Instruments de marchés à terme"),
    ("545", "Avoirs d'or et autres métaux précieux"),
    ("56", "BANQUES, CRÉDITS DE TRÉSORERIE ET D'ESCOMPTE"),
    ("561", "Crédits de trésorerie"),
    ("564", "Escompte de crédits de campagne"),
    ("565", "Escompte de crédits ordinaires"),
    ("566", "Banques, crédits de trésorerie, intérêts courus"),
    ("57", "CAISSE"),
    ("571", "Caisse siège social"),
    ("572", "Caisse succursale A"),
    ("573", "Caisse succursale B"),
    ("58", "RÉGIES D'AVANCES, ACCRÉDITIFS ET VIREMENTS INTERNES"),
    ("581", "Régies d'avance"),
    ("582", "Accréditifs"),
    ("585", "Virements de fonds (transitoire opérations internes)"),
    ("588", "Autres virements internes"),
    ("5881", "Transitoire FX (change)"),
    ("59", "DÉPRÉCIATIONS ET RISQUES PROVISIONNÉS (TRÉSORERIE)"),
    ("590", "Dépréciations des titres de placement"),
    ("591", "Dépréciations des titres et valeurs à encaisser"),
    ("592", "Dépréciations des comptes banques"),
    ("593", "Dépréciations des comptes établissements financiers et assimilés"),
    ("594", "Dépréciations des comptes d'instruments de trésorerie"),
    ("599", "Risques provisionnés à caractère financier"),

    # ------------------------------------------------------------------ CLASSE 6
    ("60", "ACHATS ET VARIATIONS DE STOCKS"),
    ("601", "Achats de marchandises"),
    ("602", "Achats de matières premières et fournitures liées"),
    ("603", "Variations des stocks de biens achetés"),
    ("604", "Achats stockés de matières et fournitures consommables"),
    ("605", "Autres achats"),
    ("608", "Achats d'emballages"),
    ("61", "TRANSPORTS"),
    ("611", "Transports sur achats"),
    ("612", "Transports sur ventes"),
    ("613", "Transports pour le compte de tiers"),
    ("614", "Transports du personnel"),
    ("616", "Transports de plis"),
    ("618", "Autres frais de transport"),
    ("62", "SERVICES EXTÉRIEURS A"),
    ("621", "Sous-traitance générale"),
    ("622", "Locations et charges locatives"),
    ("623", "Redevances de crédit-bail et contrats assimilés"),
    ("624", "Entretien, réparations et maintenance"),
    ("625", "Primes d'assurance"),
    ("626", "Études, recherches et documentation"),
    ("627", "Publicité, publications, relations publiques"),
    ("628", "Frais de télécommunications"),
    ("63", "SERVICES EXTÉRIEURS B"),
    ("631", "Frais bancaires"),
    ("632", "Rémunérations d'intermédiaires et de conseils"),
    ("633", "Frais de formation du personnel"),
    ("634", "Redevances pour brevets, licences, logiciels et droits similaires"),
    ("635", "Cotisations"),
    ("637", "Rémunérations de personnel extérieur à l'entreprise"),
    ("638", "Autres charges externes"),
    ("64", "IMPÔTS ET TAXES"),
    ("641", "Impôts et taxes directs"),
    ("645", "Impôts et taxes indirects"),
    ("646", "Droits d'enregistrement"),
    ("647", "Pénalités et amendes fiscales"),
    ("648", "Autres impôts et taxes"),
    ("65", "AUTRES CHARGES"),
    ("651", "Pertes sur créances clients et autres débiteurs"),
    ("652", "Quote-part de résultat sur opérations faites en commun"),
    ("653", "Quote-part de résultat annulée sur exécution partielle de contrats pluri-exercices"),
    ("654", "Valeur comptable des cessions courantes d'immobilisations"),
    ("658", "Charges diverses"),
    ("659", "Charges provisionnées d'exploitation"),
    ("66", "CHARGES DE PERSONNEL"),
    ("661", "Rémunérations directes versées au personnel national"),
    ("662", "Rémunérations directes versées au personnel non national"),
    ("663", "Indemnités forfaitaires versées au personnel"),
    ("664", "Charges sociales"),
    ("666", "Rémunérations et charges sociales de l'exploitant individuel"),
    ("667", "Rémunération transférée de personnel extérieur"),
    ("668", "Autres charges sociales"),
    ("67", "FRAIS FINANCIERS ET CHARGES ASSIMILÉES"),
    ("671", "Intérêts des emprunts"),
    ("672", "Intérêts dans loyers de crédit-bail et contrats assimilés"),
    ("673", "Escomptes accordés"),
    ("674", "Autres intérêts"),
    ("675", "Escomptes des effets de commerce"),
    ("676", "Pertes de change"),
    ("677", "Pertes sur cessions de titres de placement"),
    ("678", "Pertes sur risques financiers"),
    ("679", "Charges provisionnées financières"),
    ("68", "DOTATIONS AUX AMORTISSEMENTS"),
    ("681", "Dotations aux amortissements d'exploitation"),
    ("687", "Dotations aux amortissements à caractère financier"),
    ("69", "DOTATIONS AUX PROVISIONS"),
    ("691", "Dotations aux provisions d'exploitation"),
    ("697", "Dotations aux provisions financières"),

    # ------------------------------------------------------------------ CLASSE 7
    ("70", "VENTES"),
    ("701", "Ventes de marchandises"),
    ("702", "Ventes de produits finis"),
    ("703", "Ventes de produits intermédiaires"),
    ("704", "Ventes de produits résiduels"),
    ("705", "Travaux facturés"),
    ("706", "Services vendus"),
    ("7061", "Commissions sur transactions"),
    ("707", "Produits accessoires"),
    ("71", "SUBVENTIONS D'EXPLOITATION"),
    ("711", "Sur produits à l'exportation"),
    ("712", "Sur produits à l'importation"),
    ("713", "Sur produits de péréquation"),
    ("718", "Autres subventions d'exploitation"),
    ("72", "PRODUCTION IMMOBILISÉE"),
    ("721", "Immobilisations incorporelles"),
    ("722", "Immobilisations corporelles"),
    ("726", "Immobilisations financières"),
    ("73", "VARIATIONS DES STOCKS DE BIENS ET DE SERVICES PRODUITS"),
    ("734", "Variations des stocks de produits en cours"),
    ("735", "Variations des en-cours de services"),
    ("736", "Variations des stocks de produits finis"),
    ("737", "Variations des stocks de produits intermédiaires et résiduels"),
    ("75", "AUTRES PRODUITS"),
    ("752", "Quote-part de résultat sur opérations faites en commun"),
    ("753", "Quote-part de résultat sur exécution partielle de contrats pluri-exercices"),
    ("754", "Produits des cessions courantes d'immobilisations"),
    ("758", "Produits divers"),
    ("759", "Reprises de charges provisionnées d'exploitation"),
    ("77", "REVENUS FINANCIERS ET PRODUITS ASSIMILÉS"),
    ("771", "Intérêts de prêts (intérêts sur crédits)"),
    ("772", "Revenus de participations"),
    ("773", "Escomptes obtenus"),
    ("774", "Revenus de titres de placement"),
    ("776", "Gains de change"),
    ("777", "Gains sur cessions de titres de placement"),
    ("778", "Gains sur risques financiers"),
    ("779", "Reprises de charges provisionnées financières"),
    ("78", "TRANSFERTS DE CHARGES"),
    ("781", "Transferts de charges d'exploitation"),
    ("787", "Transferts de charges financières"),
    ("79", "REPRISES DE PROVISIONS"),
    ("791", "Reprises de provisions d'exploitation"),
    ("797", "Reprises de provisions financières"),
    ("798", "Reprises d'amortissements"),

    # ------------------------------------------------------- CLASSE 8 (principaux seuls)
    ("81", "VALEURS COMPTABLES DES CESSIONS D'IMMOBILISATIONS"),
    ("82", "PRODUITS DES CESSIONS D'IMMOBILISATIONS"),
    ("83", "CHARGES HORS ACTIVITÉS ORDINAIRES"),
    ("84", "PRODUITS HORS ACTIVITÉS ORDINAIRES"),
    ("85", "DOTATIONS HORS ACTIVITÉS ORDINAIRES"),
    ("86", "REPRISES HORS ACTIVITÉS ORDINAIRES"),
    ("87", "PARTICIPATION DES TRAVAILLEURS"),
    ("88", "SUBVENTIONS D'ÉQUILIBRE"),
    ("89", "IMPÔTS SUR LE RÉSULTAT"),
]

# Comptes explicitement bi-monnaie (CDF/USD) : toute la trésorerie (classe 5), plus les
# comptes de tiers/charges/produits directement liés à l'activité de crédit d'AGRICAP.
MULTI_CURRENCY_PREFIXES = ("5",)
MULTI_CURRENCY_CODES = {
    "411", "4111", "412", "4121", "416", "491", "4911",
    "676", "706", "7061", "771", "776",
}


def seed_chart(apps, schema_editor):
    ChartAccount = apps.get_model("ledger", "ChartAccount")
    by_code: dict[str, object] = {}
    for code, name in ACCOUNTS:
        if code.startswith(MULTI_CURRENCY_PREFIXES) or code in MULTI_CURRENCY_CODES:
            currencies = ["CDF", "USD"]
        else:
            currencies = []
        parent = None
        if len(code) > 2:
            parent = by_code.get(code[:-1])
        account, _ = ChartAccount.objects.get_or_create(
            code=code,
            defaults={
                "name": name, "class_no": int(code[0]), "currencies": currencies,
                "parent": parent,
            },
        )
        by_code[code] = account


def unseed_chart(apps, schema_editor):
    ChartAccount = apps.get_model("ledger", "ChartAccount")
    ChartAccount.objects.filter(code__in=[code for code, _ in ACCOUNTS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_chart, unseed_chart),
    ]
