# Generated by Django 5.2.16 on 2026-07-13 15:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default='USD', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('ACTIF', 'Actif'), ('BLOQUE', 'Bloqué')], default='ACTIF', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='accounts.fintechuser')),
            ],
        ),
        migrations.CreateModel(
            name='TreasuryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('CAISSE', 'Caisse'), ('BANQUE', 'Banque'), ('MOBILE_MONEY', 'Mobile Money')], default='CAISSE', max_length=14)),
                ('currency', models.CharField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default='USD', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('initial_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('manager_sub', models.CharField(blank=True, max_length=255)),
                ('scope', models.CharField(blank=True, max_length=120)),
                ('risk_level', models.CharField(choices=[('FAIBLE', 'Faible'), ('MODERE', 'Modéré'), ('ELEVE', 'Élevé')], default='FAIBLE', max_length=10)),
                ('status', models.CharField(choices=[('ACTIF', 'Actif'), ('EN_TRAITEMENT', 'En traitement'), ('EN_OBSERVATION', 'En observation'), ('BLOQUE', 'Bloqué'), ('ARCHIVE', 'Archivé')], default='ACTIF', max_length=14)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_accounts', to='agencies.agency')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FundTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(choices=[('CDF', 'CDF'), ('USD', 'USD')], max_length=3)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('pending_validation', 'En attente de validation'), ('approved', 'Approuvé'), ('posted', 'Comptabilisé'), ('rejected', 'Rejeté'), ('reversed', 'Annulé (contre-passé)')], default='posted', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='caisses.treasuryaccount')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='caisses.treasuryaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DEPOSIT', 'Dépôt'), ('WITHDRAW', 'Retrait'), ('FX_BUY', 'Achat devise'), ('FX_SELL', 'Vente devise')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('pending_validation', 'En attente de validation'), ('approved', 'Approuvé'), ('posted', 'Comptabilisé'), ('rejected', 'Rejeté'), ('reversed', 'Annulé (contre-passé)')], default='posted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='caisses.clientwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='clientwallet',
            constraint=models.UniqueConstraint(fields=('user', 'currency'), name='wallet_user_currency_unique'),
        ),
        migrations.AddConstraint(
            model_name='clientwallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_nonneg'),
        ),
        migrations.AddIndex(
            model_name='treasuryaccount',
            index=models.Index(fields=['agency', 'status'], name='caisses_tre_agency__e93bf6_idx'),
        ),
        migrations.AddConstraint(
            model_name='treasuryaccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='treasury_balance_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='fundtransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_account', models.F('to_account')), _negated=True), name='transfer_distinct_accounts'),
        ),
    ]
