# Generated by Django 5.2.16 on 2026-07-16 12:19

import caisses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('CDF', 'CDF'), ('USD', 'USD')], max_length=3, unique=True)),
                ('auto_limit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('manager_limit', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('pending_validation', 'En attente de validation'), ('approved', 'Approuvé'), ('posted', 'Comptabilisé'), ('rejected', 'Rejeté'), ('reversed', 'Annulé (contre-passé)')], default='pending_validation', max_length=20)),
                ('auto_validated', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_request', to='caisses.walletmovement')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='caisses.clientwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalOtpChallenge',
            fields=[
                ('id', models.CharField(default=caisses.models._generate_otp_id, max_length=36, primary_key=True, serialize=False)),
                ('approver_sub', models.CharField(max_length=255)),
                ('code_hash', models.CharField(max_length=128)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email')], default='EMAIL', max_length=10)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_challenges', to='caisses.withdrawalrequest')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_sub', models.CharField(max_length=255)),
                ('approver_role', models.CharField(max_length=40)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], max_length=10)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='caisses.withdrawalrequest')),
            ],
            options={
                'ordering': ['decided_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='withdrawalrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='withdrawal_request_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='withdrawalapproval',
            constraint=models.UniqueConstraint(fields=('request', 'approver_sub'), name='one_decision_per_withdrawal_approver'),
        ),
    ]
