# Generated by Django 5.2.16 on 2026-07-16 13:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisses', '0003_regularizationthreshold_alter_walletmovement_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryaccount',
            name='daily_ceiling',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.CreateModel(
            name='CashRegisterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('CLOSED', 'Clôturée'), ('DISCREPANCY', 'Écart constaté')], default='OPEN', max_length=12)),
                ('opened_by', models.CharField(blank=True, max_length=255)),
                ('opening_count', models.DecimalField(decimal_places=2, max_digits=18)),
                ('opening_balance_expected', models.DecimalField(decimal_places=2, max_digits=18)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('cash_in_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('closed_by', models.CharField(blank=True, max_length=255)),
                ('closing_count', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('closing_balance_expected', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('discrepancy', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_sessions', to='caisses.treasuryaccount')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
