# Generated by Django 5.2.16 on 2026-07-16 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisses', '0004_treasuryaccount_daily_ceiling_cashregistersession'),
        ('partners', '0002_partner_base_url_partner_circuit_opened_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryaccount',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_accounts', to='partners.partner'),
        ),
    ]
