# Generated by Django 5.2.16 on 2026-07-22 17:22

import caisses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisses', '0005_treasuryaccount_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmovement',
            name='kind',
            field=models.CharField(choices=[('DEPOSIT', 'Dépôt'), ('WITHDRAW', 'Retrait'), ('FX_BUY', 'Achat devise'), ('FX_SELL', 'Vente devise'), ('REGULARIZATION', 'Régularisation'), ('REVERSAL', 'Contre-passation')], max_length=14),
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, default=caisses.models._generate_payment_reference, max_length=64, unique=True)),
                ('direction', models.CharField(choices=[('COLLECTION', 'Encaissement (client → AGRICAP)'), ('PAYOUT', 'Décaissement (AGRICAP → client)')], max_length=12)),
                ('operation', models.CharField(max_length=64)),
                ('counterparty', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(choices=[('CDF', 'CDF'), ('USD', 'USD')], max_length=3)),
                ('status', models.CharField(choices=[('PENDING', "Créé — rien n'est parti"), ('SENT', 'Envoyé — aucune réponse encore enregistrée'), ('AWAITING_CONFIRMATION', 'Accusé par le fournisseur — issue non connue'), ('INDETERMINATE', 'Issue INCONNUE — à réconcilier'), ('CONFIRMED', 'Confirmé par le fournisseur'), ('REFUSED', 'Refusé par le fournisseur'), ('CANCELLED', 'Annulé avant tout envoi')], default='PENDING', max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request_path', models.CharField(blank=True, max_length=255)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=128)),
                ('last_response', models.JSONField(blank=True, null=True)),
                ('failure_detail', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_order', to='caisses.walletmovement')),
                ('reversal_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_order_reversal', to='caisses.walletmovement')),
                ('treasury_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_orders', to='caisses.treasuryaccount')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='caisses.clientwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CREATED', 'Ordre créé'), ('SENT', 'Requête envoyée'), ('RESPONSE', 'Réponse enregistrée'), ('TRANSPORT_ERROR', 'Erreur de transport — issue inconnue'), ('CONFIRMED', 'Issue confirmée'), ('REFUSED', 'Issue refusée'), ('UNCLASSIFIED', 'Réponse non classable (contrat fournisseur manquant)'), ('WALLET_POSTED', 'Mouvement de portefeuille posté'), ('WALLET_REVERSED', 'Mouvement de portefeuille contre-passé'), ('CANCELLED', 'Ordre annulé avant envoi'), ('CALLBACK_REJECTED', 'Rappel entrant refusé (non authentifié)')], max_length=24)),
                ('source', models.CharField(choices=[('SYSTEM', 'Système AGRICAP'), ('PROVIDER_RESPONSE', 'Réponse synchrone du fournisseur'), ('RECONCILIATION', 'Réconciliation (relecture de statut)'), ('CALLBACK', 'Rappel entrant du fournisseur')], default='SYSTEM', max_length=20)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(blank=True, max_length=24)),
                ('actor', models.CharField(blank=True, max_length=255)),
                ('motive', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='caisses.paymentorder')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['status'], name='payment_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['status', 'created_at'], name='payment_order_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_order_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='paymentorderevent',
            index=models.Index(fields=['order', 'at'], name='payment_event_order_at_idx'),
        ),
    ]
