# Generated by Django 5.2.16 on 2026-07-23 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisses', '0006_alter_walletmovement_kind_paymentorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='channel',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='counterparty',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_withdrawal', to='caisses.paymentorder'),
        ),
    ]
