# Generated by Django 5.2.16 on 2026-07-25 13:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisses', '0007_withdrawalrequest_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaisseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discrepancy_tolerance', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=18)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
