# Generated by Django 5.2.16 on 2026-07-13 15:40

import django.db.models.deletion
import transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('PAYMENT', 'Paiement'), ('REIMBURSEMENT', 'Remboursement'), ('TRANSFER', 'Transfert')], max_length=16, unique=True)),
                ('auto_limit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('manager_limit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('manual_timeout_hours', models.IntegerField(default=24)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('credit', 'Crédit'), ('debit', 'Débit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('emitter', models.CharField(blank=True, max_length=150)),
                ('receiver', models.CharField(blank=True, max_length=150)),
                ('operation_type', models.CharField(choices=[('PAYMENT', 'Paiement'), ('REIMBURSEMENT', 'Remboursement'), ('TRANSFER', 'Transfert')], default='PAYMENT', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('pending_validation', 'En attente de validation'), ('approved', 'Approuvé'), ('posted', 'Comptabilisé'), ('rejected', 'Rejeté'), ('reversed', 'Annulé (contre-passé)')], default='pending_validation', max_length=20)),
                ('auto_validated', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='agencies.agency')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(choices=[('MOYEN', 'Moyen'), ('ELEVE', 'Élevé'), ('CRITIQUE', 'Critique')], default='MOYEN', max_length=10)),
                ('status', models.CharField(choices=[('EN_TRANSIT', 'En transit'), ('EN_OBSERVATION', 'En observation'), ('BLOQUE', 'Bloqué')], default='EN_TRANSIT', max_length=16)),
                ('recommendation', models.TextField(blank=True)),
                ('escalated_to_sub', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_cases', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.CharField(default=transactions.models._generate_otp_id, max_length=36, primary_key=True, serialize=False)),
                ('approver_sub', models.CharField(max_length=255)),
                ('code_hash', models.CharField(max_length=128)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email')], default='EMAIL', max_length=10)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_challenges', to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_sub', models.CharField(max_length=255)),
                ('approver_role', models.CharField(max_length=40)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], max_length=10)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='transactions.transaction')),
            ],
            options={
                'ordering': ['decided_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_71abbb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['operation_type'], name='transaction_operati_57ab3f_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transactionapproval',
            constraint=models.UniqueConstraint(fields=('transaction', 'approver_sub'), name='one_decision_per_approver'),
        ),
    ]
