# Generated by Django 5.2.16 on 2026-07-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('BCC', 'BCC (officiel)'), ('STAFF', 'Interne (staff)'), ('CLIENT', 'Client (commercial)')], max_length=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('CNY', 'CNY'), ('ZAR', 'ZAR')], max_length=3)),
                ('buy_rate', models.DecimalField(decimal_places=6, max_digits=14)),
                ('sell_rate', models.DecimalField(decimal_places=6, max_digits=14)),
                ('effective_date', models.DateField()),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_date'],
                'constraints': [models.UniqueConstraint(fields=('tier', 'currency', 'effective_date'), name='fx_tier_currency_date_unique'), models.CheckConstraint(condition=models.Q(('sell_rate__gt', models.F('buy_rate'))), name='fx_sell_gt_buy')],
            },
        ),
    ]
