# Generated by Django 5.2.16 on 2026-07-22 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['-effective_date', 'usage', '-version']},
        ),
        migrations.RemoveConstraint(
            model_name='exchangerate',
            name='fx_tier_currency_date_unique',
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='reference_rate',
            field=models.ForeignKey(blank=True, help_text="Taux contre lequel l'écart a été mesuré (la veille, ou le taux corrigé).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compared_by', to='fx.exchangerate'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='source',
            field=models.CharField(choices=[('BCC', 'BCC (publication officielle)'), ('MANUELLE', 'Saisie manuelle (décision interne)'), ('AGREGATEUR', 'Agrégateur / marché constaté')], default='MANUELLE', max_length=16),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='source_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='status',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de validation (écart > seuil)'), ('ACTIF', 'Actif (taux en vigueur)'), ('REMPLACE', 'Remplacé par une version postérieure'), ('REJETE', 'Rejeté par le valideur')], db_index=True, default='ACTIF', max_length=16),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='supersedes',
            field=models.ForeignKey(blank=True, help_text='Version que ce taux remplace (chaîne de correction lisible).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='fx.exchangerate'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='threshold_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='usage',
            field=models.CharField(choices=[('OPERATIONNEL', 'Opérationnel (guichets, transactions du jour)'), ('CLOTURE', 'Clôture (arrêté comptable, états financiers)')], db_index=True, default='OPERATIONNEL', max_length=16),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='validated_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='validation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='variation_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['tier', 'currency', 'usage', 'status', '-effective_date'], name='fx_rate_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('tier', 'currency', 'effective_date', 'usage', 'version'), name='fx_rate_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIF')), fields=('tier', 'currency', 'effective_date', 'usage'), name='fx_rate_single_active'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'EN_ATTENTE')), fields=('tier', 'currency', 'effective_date', 'usage'), name='fx_rate_single_pending'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.CheckConstraint(condition=models.Q(('buy_rate__gt', 0)), name='fx_buy_strictly_positive'),
        ),
    ]
